### ISSUE TITLE
OpenTelemetry reporter is spawning gprc/netty threads

### ISSUE THREAD

**Issue by pnerg** [kamon-io/Kamon#1090]
# Issue in short
There seems to be some slowly creeping thread increase when using OTEL reporter.
There are threads related to the grpc/netty stack that for some reason just increase in count.   
I'm Using kamon v2.4.2 with the optional OTEL reporter

# App to reproduce
The app creates a single trace which I see is reported once to the OTEL reporter, then the app just idles doing nothing.   
One of course needs to have the otel-reporter library in the classpath and make sure it is started.   
For testing purposes I always use a local OTEL collector, in which I can see the trace was received.   
```scala
import kamon.Kamon
import kamon.trace.Trace.SamplingDecision
object TestIssue extends App {
  Kamon.init()

  val span = Kamon.serverSpanBuilder("dummy-op", "dummy-component")
    .samplingDecision(SamplingDecision.Sample)
    .traceId(Kamon.identifierScheme.traceIdFactory.generate())
    .start()

  Kamon.runWithSpan(span, true) {
     println("One trace coming up")
  }

  Thread.currentThread().join()
}
```
# Thread growth
Looking at the grpc/netty threads I initially see
```bash 
> jps | grep TestIssue
50664 TestIssue
```
```bash
> jstack 50664 | grep ELG
"grpc-nio-worker-ELG-1-1" #38 daemon prio=5 os_prio=31 cpu=1.30ms elapsed=1402.76s tid=0x00007ff3a2904000 nid=0x8f0b runnable  [0x000070000fb4a000]
"grpc-nio-worker-ELG-1-2" #42 daemon prio=5 os_prio=31 cpu=66.89ms elapsed=1402.59s tid=0x00007ff421b52800 nid=0x14c03 runnable  [0x0000700010568000]
```
Some time later (of idling), there's four threads
```bash
> jstack 50664 | grep ELG
"grpc-nio-worker-ELG-1-1" #38 daemon prio=5 os_prio=31 cpu=2.49ms elapsed=3881.69s tid=0x00007ff3a2904000 nid=0x8f0b runnable  [0x000070000fb4a000]
"grpc-nio-worker-ELG-1-2" #42 daemon prio=5 os_prio=31 cpu=72.10ms elapsed=3881.52s tid=0x00007ff421b52800 nid=0x14c03 runnable  [0x0000700010568000]
"grpc-nio-worker-ELG-1-3" #694 daemon prio=5 os_prio=31 cpu=2.77ms elapsed=2081.69s tid=0x00007ff401a5b800 nid=0xb123 runnable  [0x000070000eb1a000]
"grpc-nio-worker-ELG-1-4" #695 daemon prio=5 os_prio=31 cpu=0.89ms elapsed=2081.43s tid=0x00007ff401a62000 nid=0x740f runnable  [0x000070000ec1d000]
```

The threads are not really doing anything, stuck in a pool waiting for something to execute
```bash
"grpc-nio-worker-ELG-1-1" #38 daemon prio=5 os_prio=31 cpu=2.49ms elapsed=4067.76s tid=0x00007ff3a2904000 nid=0x8f0b runnable  [0x000070000fb4a000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueue.poll(java.base@11.0.9/Native Method)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(java.base@11.0.9/KQueueSelectorImpl.java:122)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.9/SelectorImpl.java:124)
        - locked <0x000000041a0b8a20> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000041a0b89c0> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(java.base@11.0.9/SelectorImpl.java:141)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:805)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.9/Thread.java:834)
```
The threads are definitely related to the OTEL exporter and its use of grpc as if I disable the reporter the threads are gone.  
 

# Real life issues  
What is bothering me is that I have components that have been running for days and in some of those this thread "leakage" continues for a loooong time. Very slowly creeping until it seems to settle at 56 threads.   
There's no gaps in the thread names (grpc-nio-worker-ELG-1-1 to grpc-nio-worker-ELG-1-56) so they have been created and then kept alive in some pool.

# Tune Netty?
The otel exporter really only instantiates a grpc channel and uses the channel to send traces.   
Everything is encapsulated in a single class [TraceService](https://github.com/kamon-io/Kamon/blob/master/reporters/kamon-opentelemetry/src/main/scala/kamon/otel/TraceService.scala) which really never touches Netty as this happens under the hood of the `io.grpc` classes.  

This issue might not be due to Kamon but by using the OTEL exporter one may experience this thread growth and hence Kamon should have some out-of-the-box tuning of Netty if that is possible

**Comment by pnerg** [comment]
As I can't let go of mind boggling issues I had to rummage through the Netty source code.... :smiley:
More specifically the [MultithreadEventLoopGroup](https://netty.io/4.0/xref/io/netty/channel/MultithreadEventLoopGroup.html#39).   
There is a reference to some magic sys.prop which I had to test:

```scala
System.setProperty("io.netty.eventLoopThreads", "1")
```
aaaand as if by magic
```bash
jstack 56958 | grep ELG | wc -l
       1
```

I'm letting my test app run for a while to see if it stays on one or will grow as before.

Perhaps this is the solution, in such case this should at least be documented on the otel-collector README
