### ISSUE TITLE
NullPointerException in jdbc.ProxyConnectionCloseMethodAdvice$.exit

### ISSUE THREAD

**Issue by kudrevatykh** [kamon-io/Kamon#1150]
Sometimes on application startup I get NPE
%%
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicReference.get()" because the return value of "kamon.instrumentation.jdbc.HasConnectionPoolTelemetry.connectionPoolTelemetry()" is null
	at kamon.instrumentation.jdbc.ProxyConnectionCloseMethodAdvice$.exit(HikariInstrumentation.scala:147) ~[kamon-bundle_2.13-2.4.5.jar:2.4.5]
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:280) ~[HikariCP-3.4.5.jar:?]
	at slick.jdbc.JdbcBackend$BaseSession.close(JdbcBackend.scala:508) ~[slick_2.13-3.3.3.jar:?]
%%
I think there is some race in Kamon instrumentation code that causes such error

**Comment by razvanz** [comment]
Looks like the instrumentation is targeting [HikariCP v4](https://github.com/kamon-io/Kamon/blob/b7904d9f654976a6963d10ea99eb6238a5464d08/build.sbt#L318). The instrumented methods have changed in v5, which is most likely the cause.

**Comment by kudrevatykh** [comment]
> Looks like the instrumentation is targeting [HikariCP v4](https://github.com/kamon-io/Kamon/blob/b7904d9f654976a6963d10ea99eb6238a5464d08/build.sbt#L318). The instrumented methods have changed in v5, which is most likely the cause.

we use HikariCP 4.0.3
