### ISSUE TITLE
"No duplicate ExecutionAttribute" when using multiple aws s3 clients with Kamon 2.5.3

### ISSUE THREAD

**Issue by hhalex** [kamon-io/Kamon#1173]
Hello there,

since last version (2.5.3), I encounter this error while using multiple aws S3 clients:

`[error] java.lang.IllegalArgumentException: No duplicate ExecutionAttribute names allowed but both ExecutionAttributes 17f26bfa and 2c7346a0 have the same name: SdkClientSpan. ExecutionAttributes should be referenced from a shared static constant to protect against erroneous or unexpected collisions.
[error] 	at software.amazon.awssdk.core.interceptor.ExecutionAttribute.ensureUnique(ExecutionAttribute.java:64)
[error] 	at software.amazon.awssdk.core.interceptor.ExecutionAttribute.<init>(ExecutionAttribute.java:58)
[error] 	at kamon.instrumentation.aws.sdk.AwsSdkClientExecutionInterceptor.<init>(AwsSdkClientExecutionInterceptor.scala:31)
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
[error] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[error] 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[error] 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
[error] 	at java.base/java.lang.Class.newInstance(Class.java:645)
[error] 	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptor(ClasspathInterceptorChainFactory.java:125)
[error] 	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptorFromResource(ClasspathInterceptorChainFactory.java:95)
[error] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
[error] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[error] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[error] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[error] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[error] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[error] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[error] 	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptorsFromClasspath(ClasspathInterceptorChainFactory.java:64)
[error] 	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.getGlobalInterceptors(ClasspathInterceptorChainFactory.java:58)
[error] 	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveExecutionInterceptors(SdkDefaultClientBuilder.java:415)
[error] 	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeConfiguration(SdkDefaultClientBuilder.java:305)
[error] 	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:206)
[error] 	at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:28)
[error] 	at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:22)
[error] 	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:145)
[error] 	at io.xxxx.AsyncClient$.$anonfun$create$1(AsyncClient.scala:25)
[error] 	at apply @ io.xxxx.AsyncClient$.create(AsyncClient.scala:17)
[error] 	at make @ io.xxxx.MetricEmitter$.io(MetricEmitter.scala:95)
[error] 	at make @ io.xxxx.MetricEmitter$.io(MetricEmitter.scala:95)
[error] 	at use @ io.xxxx.Main$.$anonfun$run$1(Main.scala:23)
[error] 	at fromSync @ io.xxxx.S3Repository$.initS3Client(S3Repository.scala:103)
[error] 	at randomString @ io.xxxx.S3Repository$.initS3Client(S3Repository.scala:103)
[error] 	at use @ io.xxxx.Main$.$anonfun$run$3(Main.scala:45)
[error] 	at apply @ io.xxxx.AsyncClient$.create(AsyncClient.scala:17)
[error] 	at make @ io.xxxx.MetricEmitter$.io(MetricEmitter.scala:95)
[error] Nonzero exit code returned from runner: 1`

**Comment by hhalex** [comment]
Thank you very much! :slightly_smiling_face:
