### ISSUE TITLE
kamon-datadog does not compatible with `okhttp3:4.x`

### ISSUE THREAD

**Issue by zerosum** [kamon-io/Kamon#1259]
versions:
- Akka `2.6.20` with kamon-datadog `2.5.12`
- Akka `2.7.0` with kamon-datadog `2.6.0`
- datadog-agent `7.41.0`

We get logs like below:
```
[ERROR] 2023-02-01 05:08:53.078 [DatadogSpanReporter] kamon.module.ModuleRegistry - Reporter [DatadogSpanReporter] failed to process a spans tick.
java.io.EOFException: 
 not found: limit=0 content=…
	at kamon.lib.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
	at kamon.lib.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at kamon.lib.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at kamon.lib.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at kamon.lib.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at kamon.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at kamon.lib.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at kamon.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at kamon.lib.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at kamon.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at kamon.lib.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at kamon.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at kamon.lib.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at kamon.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at kamon.lib.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at kamon.lib.internal.connection.RealCall.execute(RealCall.kt:154)
	at kamon.datadog.package$HttpClient.$anonfun$doRequest$1(package.scala:57)
	at scala.util.Try$.apply(Try.scala:210)
	at kamon.datadog.package$HttpClient.doRequest(package.scala:57)
	at kamon.datadog.package$HttpClient.doMethodWithBody(package.scala:65)
	at kamon.datadog.package$HttpClient.doPut(package.scala:86)
	at kamon.datadog.package$HttpClient.doJsonPut(package.scala:96)
	at kamon.datadog.DatadogSpanReporter.reportSpans(DatadogSpanReporter.scala:118)
	at kamon.module.ModuleRegistry.$anonfun$scheduleSpansBatch$1(ModuleRegistry.scala:272)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

We don't get these logs in using kamon-datadog `2.5.11`, so It seems that kamon-datadog should depends on `okhttp3 <= 3`.

related:
 - https://github.com/kamon-io/Kamon/issues/1061.
 - https://github.com/kamon-io/Kamon/pull/1226

**Comment by zerosum** [comment]
I tried to use okhttp3 `3.14.9`, then It solved.

1. modify `Kamon/build.sbt` like below
```diff
lazy val `kamon-datadog` = (project in file("reporters/kamon-datadog"))
  .enablePlugins(AssemblyPlugin)
  .settings(
    crossScalaVersions += `scala_3_version`,
    assembly / assemblyMergeStrategy := {
      case PathList("META-INF", xs @ _*)  => MergeStrategy.discard
      case _                              => MergeStrategy.first
    },
    assembly / assemblyShadeRules := Seq(
      ShadeRule.rename("okhttp3.**"                -> "kamon.lib.@1").inAll,
      ShadeRule.rename("okio.**"                   -> "kamon.lib.@1").inAll
    ),
    libraryDependencies ++= Seq(
-     okHttp % "shaded,provided",
+     "com.squareup.okhttp3" % "okhttp" % "3.14.9" % "shaded,provided",
      "com.grack" % "nanojson" % "1.6",

      ("com.typesafe.play" %% "play-json" % "2.7.4" % "test").cross(CrossVersion.for3Use2_13),
      scalatest % "test",
      slf4jApi % "test",
      slf4jnop % "test",
-     okHttpMockServer % "test"
+     "com.squareup.okhttp3" % "mockwebserver" % "3.14.9" % "test"
    )
  ).dependsOn(`kamon-core`, `kamon-testkit` % "test")
```
2. build `kamon-datadog`
```
> ++ "2.13.8"
> kamon-datadog:publishLocal
[info] :: delivering :: io.kamon#kamon-datadog_2.13;2.6.0+0-38212dc0-dirty :: 2.6.0+0-38212dc0-dirty :: integration :: Wed Feb 01 18:09:15 JST 2023
[info] 	delivering ivy file to $HOME/workspace/github.com/kamon-io/kamon/reporters/kamon-datadog/target/scala-2.13/ivy-2.6.0+0-38212dc0-dirty.xml
[info] 	published kamon-datadog_2.13 to $HOME/.ivy2/local/io.kamon/kamon-datadog_2.13/2.6.0+0-38212dc0-dirty/poms/kamon-datadog_2.13.pom
[info] 	published kamon-datadog_2.13 to $HOME/.ivy2/local/io.kamon/kamon-datadog_2.13/2.6.0+0-38212dc0-dirty/jars/kamon-datadog_2.13.jar
[info] 	published kamon-datadog_2.13 to $HOME/.ivy2/local/io.kamon/kamon-datadog_2.13/2.6.0+0-38212dc0-dirty/srcs/kamon-datadog_2.13-sources.jar
[info] 	published kamon-datadog_2.13 to $HOME/.ivy2/local/io.kamon/kamon-datadog_2.13/2.6.0+0-38212dc0-dirty/docs/kamon-datadog_2.13-javadoc.jar
[info] 	published ivy to $HOME/.ivy2/local/io.kamon/kamon-datadog_2.13/2.6.0+0-38212dc0-dirty/ivys/ivy.xml
```
3. use it in our project

**Comment by zerosum** [comment]
https://github.com/kamon-io/Kamon/pull/1270 fixed this issue as well.
Thanks @ivantopo !
