### ISSUE TITLE
Issue with Caffeine integration

### ISSUE THREAD

**Issue by Yomanz** [kamon-io/Kamon#1272]
```
WARNING: Exception thrown by stats counter
java.lang.IllegalAccessError: class kamon.instrumentation.caffeine.KamonStatsCounter tried to access private method 'void com.github.benmanes.caffeine.cache.stats.CacheStats.<init>(long, long, long, long, long, long, long)' (kamon.instrumentation.caffeine.KamonStatsCounter and com.github.benmanes.caffeine.cache.stats.CacheStats are in unnamed module of loader 'app')
	at kamon.instrumentation.caffeine.KamonStatsCounter.snapshot(KamonStatsCounter.scala:46)
	at com.github.benmanes.caffeine.cache.stats.GuardedStatsCounter.snapshot(GuardedStatsCounter.java:90)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache$AbstractCacheView.stats(LocalAsyncCache.java:569)
```
![image](https://user-images.githubusercontent.com/5119107/229824625-cc8d7a6e-7688-4adb-84ab-dcf36431ee83.png)
(Image of the private method)

I am getting this exception thrown when using kamon and caffeine together, specifically I am using Akka HTTP Prometheus metrics package which seems to be automatically hooked into by kamon.

I can provide any extra additional information as required

**Comment by ivantopo** [comment]
Hey @Yomanz, can you please share what exact Kamon/Caffeine/Java versions are you using here? Thanks!

**Comment by Yomanz** [comment]
> Hey @Yomanz, can you please share what exact Kamon/Caffeine/Java versions are you using here? Thanks!

Absolutely!

Java: Corretto 17 (Scala 2.13.7)
Kamon: 2.6.0
Caffeine: [3.1.1](https://github.com/blemale/scaffeine/blob/main/project/CaffeineVersion.scala) (Scaffeine 5.2.1)

**Comment by Yomanz** [comment]
@ivantopo I've just noticed that Kamon doesn't monitor async caffeine caches, is there a specific reason for this?
