### ISSUE TITLE
Issue while using jaeger reporter with scala

### ISSUE THREAD

**Issue by raviranjankr-mfp** [kamon-io/Kamon#1322]
I am trying to use jaeger reporter kamon-jaeger_2.13', version: '2.7.0'. but I am getting error related to okhttp

'''
12:27:24.950 [main] WARN  kamon.module.ModuleRegistry - Failed to create instance of module [Jaeger Reporter]
java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:71) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309) ~[okhttp-4.10.0.jar:?]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41) ~[okhttp-4.10.0.jar:?]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47) ~[okhttp-4.10.0.jar:?]
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471) ~[okhttp-4.10.0.jar:?]
	at io.jaegertracing.thrift.internal.senders.HttpSender$Builder.<init>(HttpSender.java:94) ~[jaeger-thrift-1.8.1.jar:1.8.1]
	at kamon.jaeger.JaegerClient$.buildCollectorClient(JaegerClient.scala:62) ~[kamon-jaeger_2.13-2.7.0.jar:2.7.0]
	at kamon.jaeger.JaegerClient$.apply(JaegerClient.scala:46) ~[kamon-jaeger_2.13-2.7.0.jar:2.7.0]
	at kamon.jaeger.JaegerReporterFactory.create(JaegerReporter.scala:27) ~[kamon-jaeger_2.13-2.7.0.jar:2.7.0]
	at kamon.module.ModuleRegistry.createModule(ModuleRegistry.scala:361) ~[kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.module.ModuleRegistry.$anonfun$load$3(ModuleRegistry.scala:124) ~[kamon-core_2.13-2.7.0.jar:2.7.0]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) ~[scala-library-2.13.12.jar:?]
	at scala.Option.fold(Option.scala:263) ~[scala-library-2.13.12.jar:?]
	at kamon.module.ModuleRegistry.$anonfun$load$2(ModuleRegistry.scala:127) ~[kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.module.ModuleRegistry.$anonfun$load$2$adapted(ModuleRegistry.scala:120) ~[kamon-core_2.13-2.7.0.jar:2.7.0]
	at scala.collection.immutable.List.foreach(List.scala:333) [scala-library-2.13.12.jar:?]
	at kamon.module.ModuleRegistry.load(ModuleRegistry.scala:120) [kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.ModuleManagement.loadModules(ModuleManagement.scala:99) [kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.ModuleManagement.loadModules$(ModuleManagement.scala:98) [kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.Kamon$.loadModules(Kamon.scala:19) [kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.Init.init(Init.scala:47) [kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.Init.init$(Init.scala:40) [kamon-core_2.13-2.7.0.jar:2.7.0]
	at kamon.Kamon$.init(Kamon.scala:19) [kamon-core_2.13-2.7.0.jar:2.7.0]
	at com.ramen.app.Events$.<clinit>(Events.scala:34) [rmn-app-events-RC-2898-kamon-jaeger-4.jar:?]
	at com.ramen.app.Events.main(Events.scala) [rmn-app-events-RC-2898-kamon-jaeger-4.jar:?]
'''

Any suggestion to resolve this issue?

Thanks

**Comment by Philippus** [comment]
Probably a dependency issue, have you checked your dependency tree?
