### ISSUE TITLE
Kamon breaks chill/kryo serialization

### ISSUE THREAD

**Issue by jeffrey-aguilera** [kamon-io/Kamon#160]
```
| 2361 | 2015-0225 | 19:52:22.412 | ERROR | Remoting                                                     | java.lang.IllegalArgumentException: Can not set kamon.trace.SegmentAware field spray.http.HttpRequest.ajc$instance$spray_can_client_ClientRequestInstrumentation$kamon_trace_SegmentAware to spray.http.HttpEntity$Empty$
Serialization trace:
ajc$instance$spray_can_client_ClientRequestInstrumentation$kamon_trace_SegmentAware (spray.http.HttpRequest)
com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Can not set kamon.trace.SegmentAware field spray.http.HttpRequest.ajc$instance$spray_can_client_ClientRequestInstrumentation$kamon_trace_SegmentAware to spray.http.HttpEntity$Empty$
Serialization trace:
ajc$instance$spray_can_client_ClientRequestInstrumentation$kamon_trace_SegmentAware (spray.http.HttpRequest)
        at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:626) ~[jetstream:SNAPSHOT]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221) ~[jetstream:SNAPSHOT]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729) ~[jetstream:SNAPSHOT]
        at com.twitter.chill.SerDeState.readClassAndObject(SerDeState.java:61) ~[jetstream:SNAPSHOT]
        at com.twitter.chill.KryoPool.fromBytes(KryoPool.java:94) ~[jetstream:SNAPSHOT]
        at com.twitter.chill.akka.AkkaSerializer.fromBinary(AkkaSerializer.scala:72) ~[jetstream:SNAPSHOT]
        at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:104) ~[jetstream:SNAPSHOT]
        at scala.util.Try$.apply(Try.scala:191) ~[jetstream:SNAPSHOT]
        at akka.serialization.Serialization.deserialize(Serialization.scala:98) ~[jetstream:SNAPSHOT]
        at akka.remote.MessageSerializer$.deserialize(MessageSerializer.scala:23) ~[jetstream:SNAPSHOT]
        at akka.remote.DefaultMessageDispatcher.payload$lzycompute$1(Endpoint.scala:58) ~[jetstream:SNAPSHOT]
        at akka.remote.DefaultMessageDispatcher.payload$1(Endpoint.scala:58) ~[jetstream:SNAPSHOT]
        at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:76) ~[jetstream:SNAPSHOT]
        at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:934) ~[jetstream:SNAPSHOT]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[jetstream:SNAPSHOT]
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:410) ~[jetstream:SNAPSHOT]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[jetstream:SNAPSHOT]
        at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487) ~[jetstream:SNAPSHOT]
        at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1) ~[jetstream:SNAPSHOT]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[jetstream:SNAPSHOT]
        at akka.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:66) ~[jetstream:SNAPSHOT]
        at akka.actor.ActorCell.invoke(ActorCell.scala:483) ~[jetstream:SNAPSHOT]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[jetstream:SNAPSHOT]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[jetstream:SNAPSHOT]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[jetstream:SNAPSHOT]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[jetstream:SNAPSHOT]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) ~[jetstream:SNAPSHOT]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) ~[jetstream:SNAPSHOT]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [jetstream:SNAPSHOT]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [jetstream:SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Can not set kamon.trace.SegmentAware field spray.http.HttpRequest.ajc$instance$spray_can_client_ClientRequestInstrumentation$kamon_trace_SegmentAware to spray.http.HttpEntity$Empty$
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164) ~[na:1.7.0_65]
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168) ~[na:1.7.0_65]
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:1.7.0_65]
        at java.lang.reflect.Field.set(Field.java:741) ~[na:1.7.0_65]
        at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:619) ~[jetstream:SNAPSHOT]
        ... 29 common frames omitted
```

**Comment by jeffrey-aguilera** [comment]
Some background:  aspectjweaver was NOT injected as a javaagent on the node that sent this message; and WAS injected on the node that received it.  The exception is thrown on the receiver node.

This seems to imply that aspectjweaver must be a configured javaagent on all nodes; it is apparently messing with serialization formats and there is no strategy for handling un-wrapped messages.

Does this assessment seem correct?

**Comment by magro** [comment]
AFAICS the spray.http.HttpRequest is serialized - is this really intended?

Cheers,
Martin
Am 26.02.2015 00:44 schrieb "Jeffrey Aguilera" <notifications@github.com>:

**Comment by jeffrey-aguilera** [comment]
Yes, it is.  The Spray folks don't like it, but I route HttpRequests to a potentially remote actor that can handle them.  That's what location transparency is all about. HttpRequests do not extend Serializable, but Chill/Kryo ships them across the cluster with ease.  (I do have to filter out some headers.)

**Comment by magro** [comment]
You could try to write a custom serializer for http request or what else is
modified by kamon, so that the FieldSerializer doesn't try to handle
everything...
Am 26.02.2015 03:42 schrieb "Jeffrey Aguilera" <notifications@github.com>:

**Comment by ivantopo** [comment]
quick question: would kryo ignore that field if it was marked as `@transient`?

**Comment by magro** [comment]
Right, that should work.
Am 26.02.2015 16:11 schrieb "Ivan Topolnjak" <notifications@github.com>:

**Comment by briantopping** [comment]
@jeffrey-aguilera: I found this because I am also working to send requests across the wire like this. Do you have any example code up?

**Comment by dpsoft** [comment]
@briantopping you can try with this snapshot version:0.6.0-a9d5c5c61f7e5e189bf67baee2b13e21ebbaaf73 that fixes the issue.

**Comment by briantopping** [comment]
Hi @dpsoft, thanks for the note, didn't realize I wasn't on akka/akka, oops! Was referring to Akka-HTTP, but am looking forward to using Kamon!
