### ISSUE TITLE
Exceptions logged on shutdown

### ISSUE THREAD

**Issue by magro** [kamon-io/Kamon#165]
After upgrading to the latest kamon snapshot 0.3.6-125bee567e0b18ea5ec10f3a1fe76409673011d9, on shutdown there are some errors logged like this:

```
[ERROR] [03/16/2015 00:04:05.846] [kamon-akka.actor.default-dispatcher-12] [ActorSystem(kamon)] exception while executing timer task
java.lang.RuntimeException: Kamon has not been started yet.
        at scala.sys.package$.error(package.scala:27)
        at kamon.Kamon$.ifStarted(Kamon.scala:83)
        at kamon.Kamon$.metrics(Kamon.scala:66)
        at akka.kamon.instrumentation.DispatcherInstrumentation.afterLazyExecutorShutdown(DispatcherInstrumentation.scala:135)
        at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.shutdown(Dispatcher.scala:43)
        at akka.dispatch.Dispatcher.shutdown(Dispatcher.scala:106)
        at akka.dispatch.MessageDispatcher$$anon$2.run(AbstractDispatcher.scala:212)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(Scheduler.scala:476)
        at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:282)
        at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:281)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280)
        at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:688)
        at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:617)
        at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:617)
        at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:617)
        at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:641)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:808)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:811)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:804)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:804)
        at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15)
        at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:804)
        at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:638)
        at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:638)
        at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:32)
        at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:44)
        at kamon.trace.Tracer$.withContext(Tracer.scala:56)
        at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:43)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:31)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I'm running `Kamon.start()` in play's Global.onStart and `Kamon.shutdown()` in onStop, perhaps this is relevant.

**Comment by ivantopo** [comment]
Martin, my guess is that Play's Akka plugin is being shutdown after Kamon was shutdown and the dispatchers instrumentation is trying to remove the dispatchers that are being shutdown, but Kamon isn't available any more... I tried to find the Play code that calls `Global.onStop(..)` with no luck and I'm not sure if this order can be altered. 

Do you have any hints on how to ensure that Play's Akka plugin is shutdown before Kamon is shutdown?

**Comment by magro** [comment]
Hmm, I tried to `Akka.system.shutdown()` directly before `Kamon.shutdown` but this didn't change anything.

**Comment by DomingoExabeam** [comment]
I am seeing the same problem. It appears to me that the problem is that kamon is killing itself.
The shutdown method is not disabling/shutting down the timer actor that collects data periodically. When this timer runs it cannot find kamon it fails. My theory is because I am seeing in the exception:
[ActorSystem(kamon)] exception while executing timer task
and also
java.lang.RuntimeException: Kamon has not been started yet.
Any ideas out there..?

**Comment by dpsoft** [comment]
@DomingoExabeam I agree with you, my guess is that kamon doesn't stop gracefully and some components still active after calling the shutdown method. Currently I finishing the integration with Play 2.4.x and the the next thing is solve this issue.

**Comment by pjan** [comment]
I was experiencing the same issue, and it happened with a configuration as follows:

```
  filters {
    akka-actor {
      includes = [ "**" ]
      excludes = [ ]
    }
  }
```

This made kamon report on it's own actors, so I updated the configuration to

```
  filters {
    akka-actor {
      includes = [ "<actorsystem_name>/**" ]
      excludes = [ ]
    }
  }
```

upon which the errors disappeared.

**Comment by enix** [comment]
It looks like the part where an Entity is removed [1] is cause the trouble;

```scala
Kamon.metrics.removeEntity(Entity(lookupData.actorSystem.name + "/" + lookupData.dispatcherName,
AkkaDispatcherMetrics.Category, tags = Map("dispatcher-type" -> "thread-pool-executor")))
``` 

The `Kamon.metrics` function [2] is implemented like so:

```scala
def metrics: MetricsModule =
  ifStarted(_.metrics)
```

The `ifStarted` call is what throws the exception. 

A possible fix might be to call the `removeEntity` function in a before hook or to keep a reference to the metrics object somewhere inside the `DispatcherInstrumentation` instance.

1: https://github.com/kamon-io/Kamon/blob/master/kamon-akka/src/main/scala/kamon/akka/instrumentation/DispatcherInstrumentation.scala#L135

2: https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/Kamon.scala#L64

**Comment by dpsoft** [comment]
we just publish a snapshot version that fixes the error: `0.4.1-6354021533319790ba675c2b9e36fb439a8ea06f`

Please let us know if anything else pops up, regards!

**Comment by enix** [comment]
@dpsoft Thanks, that fixed the reported issue. There is a similar exception occurring in the ActorCell `afterStop` call. I took a stab at it and was able fix this that using your commit as pointer. 

Please note that I've never worked with AspectJ and am new to Scala. So if there is anything that could have been done better, please let me know.

**Comment by enix** [comment]
I looked into the issue a bit deeper and can see what I did wrong. 

Perhaps there is a better way to register the `MetricsModule` for both paths but at least now the tests pass and the exception is gone.

**Comment by dpsoft** [comment]
related to #220
