### ISSUE TITLE
 kamon/util/GlobPathFilter : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by graph1zzlle** [kamon-io/Kamon#168]
Using
```
java -version
java version "1.7.0_60
```

```
[error] Exception in thread "main" java.lang.UnsupportedClassVersionError: kamon/util/GlobPathFilter : Unsupported major.minor version 52.0
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[error]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[error]         at kamon.metric.MetricsSettings$$anonfun$loadFilters$1$$anonfun$1.apply(MetricsSettings.scala:93)
[error]         at kamon.metric.MetricsSettings$$anonfun$loadFilters$1$$anonfun$1.apply(MetricsSettings.scala:93)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]         at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at kamon.metric.MetricsSettings$$anonfun$loadFilters$1.apply(MetricsSettings.scala:93)
[error]         at kamon.metric.MetricsSettings$$anonfun$loadFilters$1.apply(MetricsSettings.scala:92)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.immutable.Set$Set4.foreach(Set.scala:181)
[error]         at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[error]         at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
[error]         at scala.collection.SetLike$class.map(SetLike.scala:92)
[error]         at scala.collection.AbstractSet.map(Set.scala:47)
[error]         at kamon.metric.MetricsSettings$.loadFilters(MetricsSettings.scala:92)
```

**Comment by ivantopo** [comment]
That's weird, we build all our artifacts to be Java 1.6 compatible... which version were you using?

**Comment by graph1zzlle** [comment]
I am running 0.3.6-04677941e2253717510566cc288eab2166f7379e. For more context, I have integrated some kamon components (spray, akka, core, statsd) into my library. This library compile in for Scala 2.11.6, and I am running java 1.7.0_60.

**Comment by ivantopo** [comment]
Can you please try `0.3.6-0cb49a7cc94a7a2040b0a8ffdba2cff395a0c0e8` for Scala 2.11? That's the latest snapshot we published and it should work correctly.

**Comment by graph1zzlle** [comment]
Yes, I will give it a try asap. Thanks !

**Comment by ivantopo** [comment]
@graph1zzlle did this work for you?

**Comment by ivantopo** [comment]
As of fc86654c2ff451fa222677b27a5b45e024b93f61 this issue was finally corrected.
