### ISSUE TITLE
ArrayIndexOutOfBounds exception in AtomicHistogram

### ISSUE THREAD

**Issue by jeroentervoorde** [kamon-io/Kamon#170]
After running our application for some time it started generating these exceptions. We are using the following artifacts:

    "org.aspectj" % "aspectjweaver" % "1.8.5"
    "io.kamon" %% "kamon-core" % "0.3.5",
    "io.kamon" %% "kamon-datadog" % "0.3.5",
    "io.kamon" %% "kamon-play" % "0.3.5"

Play version is 2.3.3 and scala version is 2.11.5.

Any idea what could be causing this?

Jeroen

ERROR akka.actor.ActorSystemImpl - Uncaught error from thread [connect-akka.actor.thread-pool-dispatcher-165469]
java.lang.IndexOutOfBoundsException: index 4618
at java.util.concurrent.atomic.AtomicLongArray.checkedByteOffset(AtomicLongArray.java:64) ~[na:1.7.0_76]
	at java.util.concurrent.atomic.AtomicLongArray.addAndGet(AtomicLongArray.java:256) ~[na:1.7.0_76]
	at java.util.concurrent.atomic.AtomicLongArray.incrementAndGet(AtomicLongArray.java:235) ~[na:1.7.0_76]
	at org.HdrHistogram.AtomicHistogram.incrementCountAtIndex(AtomicHistogram.java:36) ~[org.hdrhistogram.HdrHistogram-1.2.1.jar:0.3.5]
	at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:285) ~[org.hdrhistogram.HdrHistogram-1.2.1.jar:0.3.5]
	at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:216) ~[org.hdrhistogram.HdrHistogram-1.2.1.jar:0.3.5]
	at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:109) ~[io.kamon.kamon-core_2.11-0.3.5.jar:0.3.5]
	at akka.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:69) ~[io.kamon.kamon-core_2.11-0.3.5.jar:0.3.5]
	at akka.actor.ActorCell.invoke(ActorCell.scala:483) ~[com.typesafe.akka.akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) ~[com.typesafe.akka.akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) ~[com.typesafe.akka.akka-actor_2.11-2.3.6.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_76]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_76]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_76]
java.lang.IndexOutOfBoundsException: index 4618
	at java.util.concurrent.atomic.AtomicLongArray.checkedByteOffset(AtomicLongArray.java:64)
	at java.util.concurrent.atomic.AtomicLongArray.addAndGet(AtomicLongArray.java:256)
	at java.util.concurrent.atomic.AtomicLongArray.incrementAndGet(AtomicLongArray.java:235)
	at org.HdrHistogram.AtomicHistogram.incrementCountAtIndex(AtomicHistogram.java:36)
	at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:285)
	at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:216)
	at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:109)
	at akka.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:69)
	at akka.actor.ActorCell.invoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ivantopo** [comment]
Hello, it seems to me that you are having the same problem that I describe in [this] comment... do you usually have requests that take longer than one hour to be processed?

[this]: https://github.com/kamon-io/Kamon/issues/71#issuecomment-63090925

**Comment by jeroentervoorde** [comment]
Hi,


It might be an actor message that's taking very long to process. I guess this could also result in this error? Do you know if the exception happens after the message

has been processed or could it also happen during processing? Is there some way to log which message / actor causes the problem?


Thanks,

Jeroen


Met vriendelijke groet,

         
OVSoftware bv Burg. Wallerstraat 179 7574 AN Oldenzaal T +31 541 533111 F +31 541 533112   www.ovsoftware.nl  disclaimer
________________________________
Van: Ivan Topolnjak <notifications@github.com>
Verzonden: dinsdag 24 maart 2015 19:02
Aan: kamon-io/Kamon
CC: Jeroen ter Voorde
Onderwerp: Re: [Kamon] ArrayIndexOutOfBounds exception in AtomicHistogram (#170)


Hello, it seems to me that you are having the same problem that I describe in this<https://github.com/kamon-io/Kamon/issues/71#issuecomment-63090925> comment... do you usually have requests that take longer than one hour to be processed?

-

**Comment by jeroentervoorde** [comment]
Hi Ivan,


Yesterday i did some profiling on our server and i noticed a huge amount of trace segments in memory. These seem to be caused by an actor which uploads files

to S3 using the play WS library. I assumed a new segment was created for every file that was uploaded (which always has a unique name). Is this a known issue which

i have to fix in code by setting the trace name?


Thanks,

Jeroen


Met vriendelijke groet,



J (Jeroen) ter Voorde
IT Professional

         
OVSoftware bv Burg. Wallerstraat 179 7574 AN Oldenzaal T +31 541 533111 F +31 541 533112   www.ovsoftware.nl  disclaimer
________________________________
Van: Ivan Topolnjak <notifications@github.com>
Verzonden: dinsdag 24 maart 2015 19:02
Aan: kamon-io/Kamon
CC: Jeroen ter Voorde
Onderwerp: Re: [Kamon] ArrayIndexOutOfBounds exception in AtomicHistogram (#170)


Hello, it seems to me that you are having the same problem that I describe in this<https://github.com/kamon-io/Kamon/issues/71#issuecomment-63090925> comment... do you usually have requests that take longer than one hour to be processed?

-

**Comment by ivantopo** [comment]
Hello @jeroentervoorde, the exception is definitely thrown after the message has been processed, there is no way it could have happened while the message is being processed because the instrumentation for a given actor records right after the call to the receive function finishes. We currently don't offer a way to log the messages that cause these failures but we know for sure that a message should have been in the mailbox or being processed for more than 1 hour for this issue to be triggered.

Just by increasing the highest trackable value in the HDR configuration to a suitable value you can we rid of this problem.

**Comment by ivantopo** [comment]
To your second issue, you definitely need to do a couple changes to ensure that the segments get real and understandable names. By default the segments generated from the WS client instrumentation will be named after the [request url] (we should do something about that), but you can define your own [PlayNameGenerator] and add it to your application [config file] so that Kamon will use that for naming segments. 

If you use the provided WSRequest object to determine if the request is going to Amazon S3 and you assign a name like "S3Upload" then all the requests to S3 for the given trace will be grouped under that segment name, which is the original spirit of using trace segments :).

Please keep asking if you need any help setting up the segments names.. also, are you customizing your trace names or leaving the default ones?

[request url]: https://github.com/kamon-io/Kamon/blob/v0.3.5/kamon-play/src/main/scala/kamon/play/Play.scala#L59
[PlayNameGenerator]: https://github.com/kamon-io/Kamon/blob/v0.3.5/kamon-play/src/main/scala/kamon/play/Play.scala#L52
[config file]: https://github.com/kamon-io/Kamon/blob/v0.3.5/kamon-play/src/main/resources/reference.conf#L22

**Comment by jeroentervoorde** [comment]
Hi Ivan,


Thanks for your clarifications. For now i've disabled to play metrics as we were mostly interested in akka logging anyway. Currently we are using default names

for everything. I'll put an issue on the backlog for creating our PlayNameGenerator.


Thanks,

Jeroen



Met vriendelijke groet,



J (Jeroen) ter Voorde
IT Professional

         
OVSoftware bv Burg. Wallerstraat 179 7574 AN Oldenzaal T +31 541 533111 F +31 541 533112   www.ovsoftware.nl  disclaimer
________________________________
Van: Ivan Topolnjak <notifications@github.com>
Verzonden: vrijdag 27 maart 2015 21:01
Aan: kamon-io/Kamon
CC: Jeroen ter Voorde
Onderwerp: Re: [Kamon] ArrayIndexOutOfBounds exception in AtomicHistogram (#170)


To your second issue, you definitely need to do a couple changes to ensure that the segments get real and understandable names. By default the segments generated from the WS client instrumentation will be named after the request url<we%20should%20do%20something%20about%20that>, but you can define your own PlayNameGenerator<https://github.com/kamon-io/Kamon/blob/v0.3.5/kamon-play/src/main/scala/kamon/play/Play.scala#L52> and add it to your application config file<https://github.com/kamon-io/Kamon/blob/v0.3.5/kamon-play/src/main/resources/reference.conf#L22> so that Kamon will use that for naming segments.

If you use the provided WSRequest object to determine if the request is going to Amazon S3 and you assign a name like "S3Upload" then all the requests to S3 for the given trace will be grouped under that segment name, which is the original spirit of using trace segments :).

Please keep asking if you need any help setting up the segments names.. also, are you customizing your trace names or leaving the default ones?

-

**Comment by ivantopo** [comment]
Nice, tell me one thing: did the original issue get solved for you? The ArrayIndexOutOfBoundsException? Just to know if we can close this issue.

**Comment by ivantopo** [comment]
I'm assuming that the problem was solved, please feel free to reopen or comment if it wasn't the case, regards!
