### ISSUE TITLE
Unable to find class 'akka.event.Logging.LogEvent' in repository

### ISSUE THREAD

**Issue by osbornk** [kamon-io/Kamon#183]
I am getting 7-8 of these messages on startup:

ava.lang.ClassNotFoundException: akka.event.Logging.LogEvent not found - unable to determine URL
	at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.5.jar:1.8.5]
	at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.5.jar:1.8.5]
	at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.5.jar:1.8.5]
	at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.5.jar:1.8.5]
	at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.5.jar:1.8.5]

This is an Akka Play application.

I am starting the application with the following command:

activator -jvm-debug 9999 -Dhttps.port=9443 -J-javaagent:/Users/Me/.ivy2/cache/org.aspectj/aspectjweaver/jars/aspectjweaver-1.8.5.jar

In application.conf, I have this:

akka {
  extensions = ["kamon.metric.Metrics", "kamon.logreporter.LogReporter"]
}

I have also imported kamon-core, kamon-play, kamon-log-reporter, and kamon-system-metrics in my build.sbt,

In build.stb, I have tried setting "fork in run" to both true and false. Is there anything else I should be doing?

**Comment by hsun-cnnxty** [comment]
I got the same issue here.

**Comment by ivantopo** [comment]
Hello there! Sorry for taking too long to jump into this. Did you guys find any solution to this issue?.. BTW, setting `fork in run := true` for Play! applications doesn't have any effect as Play!'s internals wont allow the JVM to be forked.

**Comment by osbornk** [comment]
I never did. But I also got tasked to other issues, so I have not taken a look again in a while.

**Comment by Honigbaum** [comment]
Same here. Any solution?

**Comment by ksnagendran** [comment]
I'm also facing the same issue, any body know the answer pls update in this post

**Comment by dpsoft** [comment]
Play have some limitations when trying to set a java agent in `dev mode` (ie, play run) -> https://github.com/playframework/playframework/issues/1372.

**Comment by Honigbaum** [comment]
We're also facing this problem in `prod mode`

**Comment by dpsoft** [comment]
how you are runnig the application in prod? in this manner `java -cp ".:lib/*" -javaagent:lib/org.aspectj.aspectjweaver-1.8.5.jar play.core.server.NettyServer`?

you are running other agent like new relic?

**Comment by Honigbaum** [comment]
we're using the script generated by play `bin/myapp.sh -J-javaagent:/myapp/lib/org.aspectj.aspectjweaver-1.8.5.jar`

**Comment by hsun-cnnxty** [comment]
With Play:

bin/my-service -v -J-javaagent:lib/aspectjweaver-1.8.5.jar 

Above command-line works for me.

**Comment by ksnagendran** [comment]
I'm trying to run in dev mode as 

activator run  -J-javaagent:"aspectjweaver-1.8.3.jar"

and getting errors as 

[error] o.a.w.b.BcelWorld - Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.event.Logging.LogEvent' in repository
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.dispatch.Dispatcher.LazyExecutorServiceDelegate' in repository

**Comment by avdv** [comment]
Hi.

I think I'm running into the same problem. Versions:

* scala 2.11.6
* play 2.3.9
* kamon 0.4.0
* aspectjweaver 1.8.6

The application is run in prod mode, using the script generated by "./activator dist", ie. `./bin/app-server -J-javaagent:aspectjweaver.jar`.

Error messages:

```
[INFO] [06/17/2015 15:48:55.953] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[INFO] [06/17/2015 15:48:56.038] [main] [PlayExtension(akka://kamon)] Starting the Kamon(Play) extension
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9090
[error] o.a.w.b.BcelWorld - Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'scala.concurrent.impl.Future.PromiseCompletingRunnable' in repository
java.lang.ClassNotFoundException: scala.concurrent.impl.Future.PromiseCompletingRunnable not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.event.Logging.LogEvent' in repository
java.lang.ClassNotFoundException: akka.event.Logging.LogEvent not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.event.Logging.LogEvent' in repository
java.lang.ClassNotFoundException: akka.event.Logging.LogEvent not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.dispatch.Dispatcher.LazyExecutorServiceDelegate' in repository
java.lang.ClassNotFoundException: akka.dispatch.Dispatcher.LazyExecutorServiceDelegate not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.dispatch.Dispatcher.LazyExecutorServiceDelegate' in repository
java.lang.ClassNotFoundException: akka.dispatch.Dispatcher.LazyExecutorServiceDelegate not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.dispatch.Dispatcher.LazyExecutorServiceDelegate' in repository
java.lang.ClassNotFoundException: akka.dispatch.Dispatcher.LazyExecutorServiceDelegate not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
[error] o.a.w.b.BcelWorld - Unable to find class 'akka.dispatch.Dispatcher.LazyExecutorServiceDelegate' in repository
java.lang.ClassNotFoundException: akka.dispatch.Dispatcher.LazyExecutorServiceDelegate not found - unable to determine URL
        at org.aspectj.apache.bcel.util.ClassLoaderRepository.loadClass(ClassLoaderRepository.java:292) ~[aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:418) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:392) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.ltw.LTWWorld.resolveDelegate(LTWWorld.java:107) [aspectjweaver-1.8.6.jar:1.8.6]
        at org.aspectj.weaver.World.resolveToReferenceType(World.java:477) [aspectjweaver-1.8.6.jar:1.8.6]
```

**Comment by dpsoft** [comment]
Hi,

you can try with this:

* 1- play stage
* 2- cd target/universal/stage
* 3- java -cp ".:lib/*" -javaagent:lib/org.aspectj.aspectjweaver-1.8.6.jar
play.core.server.NettyServer

cheers,

Diego

**Comment by avdv** [comment]
@dpsoft: this works on my local machine, just as well as using the script generated by activator.

**Comment by dpsoft** [comment]
@avdv you are running other agent like new relic?

**Comment by avdv** [comment]
> you are running other agent like new relic?

no, I used to run Jolokia, but already eliminated that as a the source the errors. But I'll double-check tomorrow.

**Comment by ksnagendran** [comment]
I tried this

* 1- play stage
* 2- cd target/universal/stage
* 3- java -cp ".:lib/*" -javaagent:lib/org.aspectj.aspectjweaver-1.8.6.jar
play.core.server.NettyServer

and now i'm not getting the classnotfoundexceptions, thanks @dpsoft 

but when starting the kamon i'm getting this error

[INFO] [06/22/2015 16:20:09.878] [main] [SystemMetricsExtension(akka://kamon)] Starting the Kamon(SystemMetrics) extension
1 [main] DEBUG Sigar  - no libsigar-universal64-macosx.dylib in java.library.path
org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path

**Comment by dpsoft** [comment]
Hi,

the sigar-loader library will try to load sigar first, and if it fails then
it will provision and load the appropriate native library and then
instantiate sigar again so, the first failure that always happens is
causing the error you see, but then after that it is correcting the problem
by provisioning and then loading, so that is something we should change
though.. it looks like there is an error, but there actually isn't any

cheers,

Diego

**Comment by ksnagendran** [comment]
Thanks @dpsoft for your quick response.
What is the reason for "No metrics reported" for Actor Metrics

**Comment by ksnagendran** [comment]
Now i can see the logs as like below. Processing time and time in mail box showing zero values.

Actor: test/user/simple-service-actor                                                         |
|                                                                                                  |
|   Processing Time (nanoseconds)      Time in Mailbox (nanoseconds)         Mailbox Size          |
|    Msg Count: 0                                       Msg Count: 0                                        Min: 0              |
|    Min: 0                                                   Min: 0                                                 Avg.: 0.0            |
|    50th Perc: 0                                          50th Perc: 0                                        Max: 15             |
|    90th Perc: 0                                          90th Perc: 0                                       |
|    95th Perc: 0                                         95th Perc: 0                                      |
|    99th Perc: 0                                         99th Perc: 0                                     Error Count: 0        |
|    99.9th Perc: 0                                      99.9th Perc: 0                                      |
|    Max: 0                                                  Max: 0

**Comment by dpsoft** [comment]
@osbornk,  Guys, we have been worked in a sbt plugin that allow perform LTW in sbt and we will be able to do  run in development mode in play seamlessly. [sbt-aspectj-runner]. Enjoy!!!!!

[sbt-aspectj-runner]: https://github.com/kamon-io/sbt-aspectj-runner
