### ISSUE TITLE
NPE in ActorCellInstrumention.beforeInvokeFailure

### ISSUE THREAD

**Issue by jamesmulcahy** [kamon-io/Kamon#184]
Running 0.3.6-fc86654c2ff451fa222677b27a5b45e024b93f61, I've just hit the following.  Not sure what I did to trigger it, as my config relating to Kamon and/orrouters hasn't changed lately.

```
cc2 [ERROR] [04/21/2015 14:24:06.493] [cloud-controller-akka.actor.default-dispatcher-16] [ActorSystem(cloud-controller)] Uncaught error from thread [cloud-controller-akka.actor.default-dispatcher-16]
cc2 java.lang.NullPointerException
cc2 	at akka.kamon.instrumentation.ActorCellInstrumentation.beforeInvokeFailure(ActorCellInstrumentation.scala:120)
cc2 	at akka.actor.ActorCell.handleInvokeFailure(ActorCell.scala:369)
cc2 	at akka.actor.ActorCell$$anonfun$2.apply(ActorCell.scala:467)
cc2 	at akka.actor.ActorCell$$anonfun$2.apply(ActorCell.scala:466)
cc2 	at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:302)
cc2 	at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:297)
cc2 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
cc2 	at akka.actor.ActorCell.invokeAll$1_aroundBody2(ActorCell.scala:466)
cc2 	at akka.actor.ActorCell$AjcClosure3.run(ActorCell.scala:1)
cc2 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
cc2 	at akka.kamon.instrumentation.ActorSystemMessageInstrumentation$$anonfun$aroundSystemMessageInvoke$1.apply(ActorSystemMessageInstrumentation.scala:34)
cc2 	at kamon.trace.Tracer$.withContext(Tracer.scala:56)
cc2 	at akka.kamon.instrumentation.ActorSystemMessageInstrumentation.aroundSystemMessageInvoke(ActorSystemMessageInstrumentation.scala:34)
cc2 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:1)
cc2 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
cc2 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
cc2 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
cc2 	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
cc2 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
cc2 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
cc2 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
cc2 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by jamesmulcahy** [comment]
I've tracked this back to occurring when another exception is thrown during the initialization of an Actor.  I'm guessing that the full Kamon init isn't complete, and in trying to log a stat before init has completed, it runs into this NPE.

If I disable AspectJ weaving, the underlying exception occurs due to a context.system.settings.config.getInt inside the constructor for an Actor.

Stacktrace was:

```
cc2 [ERROR] [04/21/2015 14:41:00.739] [REDACTED-akka.actor.default-dispatcher-18] [akka://REDACTED] No configuration setting found for key 'REDACTED.cache'
cc2 akka.actor.ActorInitializationException: exception during creation
cc2 	at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
cc2 	at akka.actor.ActorCell.create(ActorCell.scala:596)
cc2 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
cc2 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
cc2 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
cc2 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
cc2 	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
cc2 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
cc2 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
cc2 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
cc2 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
cc2 Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'REDACTED'
cc2 	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
cc2 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:147)
cc2 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
cc2 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
cc2 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
cc2 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
cc2 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
cc2 	at com.typesafe.config.impl.SimpleConfig.getConfigNumber(SimpleConfig.java:179)
cc2 	at com.typesafe.config.impl.SimpleConfig.getInt(SimpleConfig.java:190)
REDACTED
REDACTED
REDACTED
cc2 	at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343)
cc2 	at akka.actor.Props.newActor(Props.scala:252)
cc2 	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
cc2 	at akka.actor.ActorCell.create(ActorCell.scala:578)
cc2 	... 9 more
```

**Comment by ivantopo** [comment]
Hey @jamesmulcahy! Thanks for reporting this issue, We really appreciate all the feedback that you have been sharing lately which certainly will make Kamon a better tool! I'll try to find a way to reproduce this issue with the info you provided and get back to you.

**Comment by jamesmulcahy** [comment]
Hey Ivan - No problem - happy to help & pleased you're taking them as constructive - I'm not trying to beat up on you guys, you're doing a great job :)

**Comment by ivantopo** [comment]
thanks, James! As per your description, a failure while processing a system message was triggering some instrumentation that we didn't expect and that caused the NPE... The snapshot version `0.3.6-a2840a7020df81056a656d3e88be223f7af62ac6` including this fix is being uploaded now to the snapshots repo and you should be able to pull it in a couple minutes.

Please let us know if anything else pops up, regards!
