### ISSUE TITLE
Integrate with Java

### ISSUE THREAD

**Issue by varunachar** [kamon-io/Kamon#189]
I'm using Java to program with Akka. I have configured the project using Maven and using the standard maven structure. What are the steps to integrate Kamon with Java?

**Comment by dpsoft** [comment]
@varunachar we published our latest WIP with regards to documentation at http://master.kamon.io/introduction/get-started/, please take a look at it and feedback is welcome!!

**Comment by varunachar** [comment]
I'm getting the following error when integrating it with Java.
```java

Caused by: java.lang.RuntimeException: Kamon has not been started yet.
	at scala.sys.package$.error(package.scala:27)
	at kamon.Kamon$.ifStarted(Kamon.scala:82)
	at kamon.Kamon$.metrics(Kamon.scala:65)
	at akka.kamon.instrumentation.ActorCellInstrumentation.afterCreation(ActorCellInstrumentation.scala:42)
	at akka.actor.ActorCell.<init>(ActorCell.scala:397)
	at akka.actor.LocalActorRef.newActorCell(ActorRef.scala:307)
	at akka.actor.LocalActorRef.<init>(ActorRef.scala:303)
	at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:720)
```

Kamon Configuration:

```
akka {
    loglevel = "DEBUG"
    stdout-loglevel = "DEBUG"
    actor {
        default-dispatcher {
            type = Dispatcher
            executor = "fork-join-executor"
            fork-join-executor {
                parallelism-min = 2
                parallelism-factor = 2.0
                parallelism-max = 10
            }
            throughput = 100
        }
    }
}

kamon.metric.filters {
  akka-actor {
    includes = [ "AkkaJavaSpring/user/**"]
    excludes = [ "AkkaJavaSpring/system/**" ]
  }

  akka-dispatcher {
    includes = [ "AkkaJavaSpring/akka.actor.default-dispatcher"]
  }
}
```

```java
public class App {

    public static void main(String[] args) {
        Kamon.start();
        
        final Histogram someHistogram = Kamon.metrics().histogram("some-histogram");
        final Counter someCounter = Kamon.metrics().counter("some-counter");
        
        someHistogram.record(42);
        someHistogram.record(50);
        someCounter.increment();
        
        SpringApplication.run(AppConfiguration.class, args);
        Kamon.shutdown();
    }
}
```

**Comment by ivantopo** [comment]
Hello @varunachar! Do you know if the call to `SpringApplication.run(...)` blocks the main thread or not? I guess it doesn't and then you are shutting down Kamon while some other parts of your application might want to use it.
