### ISSUE TITLE
java.lang.IndexOutOfBoundsException in HdrHistogram

### ISSUE THREAD

**Issue by SBozhko** [kamon-io/Kamon#193]
Hi, we have many such errors:
```
java.lang.IndexOutOfBoundsException: index 3222
	at java.util.concurrent.atomic.AtomicLongArray.checkedByteOffset(AtomicLongArray.java:64) ~[na:1.7.0_40]
	at java.util.concurrent.atomic.AtomicLongArray.addAndGet(AtomicLongArray.java:256) ~[na:1.7.0_40]
	at java.util.concurrent.atomic.AtomicLongArray.incrementAndGet(AtomicLongArray.java:235) ~[na:1.7.0_40]
	at org.HdrHistogram.AtomicHistogram.incrementCountAtIndex(AtomicHistogram.java:36) ~[HdrHistogram-1.2.1.jar:0.3.5]
	at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:285) ~[HdrHistogram-1.2.1.jar:0.3.5]
	at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:216) ~[HdrHistogram-1.2.1.jar:0.3.5]
	at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:109) ~[kamon-core_2.11-0.3.5.jar:0.3.5]
	at kamon.system.SystemMetricsCollector.kamon$system$SystemMetricsCollector$$recordProcessCpu(SystemMetricsCollector.scala:78) ~[data-processing-api-commons-1.5.1.jar:0.3.5]
	at kamon.system.SystemMetricsCollector.collectMetrics(SystemMetricsCollector.scala:58) ~[data-processing-api-commons-1.5.1.jar:0.3.5]
	at kamon.system.SystemMetricsCollector$$anonfun$receive$1.applyOrElse(SystemMetricsCollector.scala:50) ~[data-processing-api-commons-1.5.1.jar:0.3.5]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.6.jar:na]
	at kamon.system.SystemMetricsCollector.aroundReceive(SystemMetricsCollector.scala:37) ~[data-processing-api-commons-1.5.1.jar:0.3.5]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.6.jar:na]
	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487) [akka-actor_2.11-2.3.6.jar:na]
	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1) [akka-actor_2.11-2.3.6.jar:na]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) [aspectjweaver-1.8.3.jar:1.8.3]
	at akka.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:66) [kamon-core_2.11-0.3.5.jar:0.3.5]
	at akka.actor.ActorCell.invoke(ActorCell.scala:483) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
```

Dependencies: 
```
<kamon.version>0.3.5</kamon.version>
<akka.version>2.3.6</akka.version>
<spray.version>1.3.2</spray.version>

        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-core_2.11</artifactId>
            <version>${kamon.version}</version>
        </dependency>
        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-statsd_2.11</artifactId>
            <version>${kamon.version}</version>
        </dependency>
        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-log-reporter_2.11</artifactId>
            <version>${kamon.version}</version>
        </dependency>
        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-spray_2.11</artifactId>
            <version>${kamon.version}</version>
        </dependency>
        <dependency>
            <groupId>io.kamon</groupId>
            <artifactId>kamon-system-metrics_2.11</artifactId>
            <version>${kamon.version}</version>
        </dependency>
```

**Comment by ivantopo** [comment]
Hello Svetlana! Is it correct to assume that this problem happens after your application has been running for quite some time?

We removed the CPU time metric from the ProcessCpu recorder for the next release so this shouldn't be an issue anymore, but you will need to upgrade to fix this problem.. is it possible for you to do so?

**Comment by SBozhko** [comment]
Yes, application was running quite stable for a long time without such errors.

I think it's possible to upgrade, but... do you have substitutional tool for CPU time metric? Or any other suggestions regarding this?

**Comment by ivantopo** [comment]
The cpu-time metrics where removed mainly because it's values are ever growing and not that much interesting if we switch to diff-recording the cpu-time, but we do have CPU usage percentage for both the overall system and the process, also differentiating between user and system cpu in both cases.. would that work for you?

**Comment by dpsoft** [comment]
@SBozhko we will proceed to close this issue.
