### ISSUE TITLE
NPE when initializing a balancing-pool router from configuration

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#199]
See https://groups.google.com/forum/#!topic/kamon-user/uHlS2sH-h7Q

here is the StackTrace:

```
akka.ConfigurationException: configuration problem while creating [akka://ia/user/CoreCoordinator/EvaluationSupervisor/DocumentPropertyEvaluatorManager/DocumentPropertyEvaluator] with router dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox] and routee dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox]
 at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:752) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.dungeon.Children$class.makeChild(Children.scala:206) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.dungeon.Children$class.actorOf(Children.scala:37) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.ActorCell.actorOf(ActorCell.scala:369) [akka-actor_2.10-2.3.9.jar:na]
 at uk.co.datasys.core.actor.evaluation.evaluators.documentproperty.DocumentPropertyEvaluatorManager.updateDocumentPropertyEvaluator(DocumentPropertyEvaluatorManager.java:110) ~[DocumentPropertyEvaluatorManager.class:na]
 at uk.co.datasys.core.actor.evaluation.evaluators.documentproperty.DocumentPropertyEvaluatorManager.processEvaluatorRules(DocumentPropertyEvaluatorManager.java:92) ~[DocumentPropertyEvaluatorManager.class:na]
 at uk.co.datasys.core.actor.evaluation.evaluators.documentproperty.DocumentPropertyEvaluatorManager$$Lambda$179/1850206261.apply(Unknown Source) ~[na:na]
 at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21) ~[akka-actor_2.10-2.3.9.jar:na]
 at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118) ~[scala-library-2.10.5.jar:na]
 at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21) ~[akka-actor_2.10-2.3.9.jar:na]
 at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165) ~[scala-library-2.10.5.jar:na]
 at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487) [akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1) [na:na]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) [aspectjweaver.jar:1.8.4]
 at akka.kamon.instrumentation.ActorCellInstrumentation$$anonfun$aroundBehaviourInvoke$1.apply(ActorCellInstrumentation.scala:62) [kamon-akka_2.10-0.4.0.jar:0.4.0]
 at kamon.trace.Tracer$.withContext(TracerModule.scala:57) [kamon-core_2.10-0.4.0.jar:0.4.0]
 at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:61) [kamon-akka_2.10-0.4.0.jar:0.4.0]
 at akka.actor.ActorCell.invoke(ActorCell.scala:483) [akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.10-2.3.9.jar:na]
 at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.5.jar:na]
 at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.5.jar:na]
 at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.5.jar:na]
 at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.5.jar:na]
Caused by: java.lang.NullPointerException: null
 at akka.kamon.instrumentation.DispatcherInstrumentation.afterCreateExecutorService(DispatcherInstrumentation.scala:101) ~[kamon-akka_2.10-0.4.0.jar:0.4.0]
 at akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory.createExecutorService(AbstractDispatcher.scala:426) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor$lzycompute(Dispatcher.scala:44) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor(Dispatcher.scala:44) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.ExecutorServiceDelegate$class.execute(ThreadPoolBuilder.scala:212) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:43) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:118) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:133) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.dungeon.Dispatch$class.start(Dispatch.scala:87) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.ActorCell.start(ActorCell.scala:369) [akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.LocalActorRef.start(ActorRef.scala:321) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.dungeon.Children$class.makeChild(Children.scala:220) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.dungeon.Children$class.actorOf(Children.scala:35) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.ActorCell.actorOf(ActorCell.scala:369) [akka-actor_2.10-2.3.9.jar:na]
 at akka.routing.BalancingPool.newRoutee(Balancing.scala:121) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.routing.RoutedActorCell$$anonfun$start$3.apply(RoutedActorCell.scala:116) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.routing.RoutedActorCell$$anonfun$start$3.apply(RoutedActorCell.scala:116) ~[akka-actor_2.10-2.3.9.jar:na]
 at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:91) ~[scala-library-2.10.5.jar:na]
 at akka.routing.RoutedActorCell.start(RoutedActorCell.scala:116) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.routing.RoutedActorCell.start(RoutedActorCell.scala:41) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.RepointableActorRef.point_aroundBody0(RepointableActorRef.scala:105) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.RepointableActorRef$AjcClosure1.run(RepointableActorRef.scala:1) ~[na:na]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) [aspectjweaver.jar:1.8.4]
 at akka.kamon.instrumentation.TraceContextIntoRepointableActorRefMixin$$anonfun$afterRepointableActorRefCreation$1.apply(ActorSystemMessageInstrumentation.scala:77) ~[kamon-akka_2.10-0.4.0.jar:0.4.0]
 at kamon.trace.Tracer$.withContext(TracerModule.scala:57) [kamon-core_2.10-0.4.0.jar:0.4.0]
 at akka.kamon.instrumentation.TraceContextIntoRepointableActorRefMixin.afterRepointableActorRefCreation(ActorSystemMessageInstrumentation.scala:76) ~[kamon-akka_2.10-0.4.0.jar:0.4.0]
 at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:94) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.RepointableActorRef.initialize(RepointableActorRef.scala:82) ~[akka-actor_2.10-2.3.9.jar:na]
 at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:750) ~[akka-actor_2.10-2.3.9.jar:na]
 ... 28 common frames omitted
```

**Comment by kholodilov** [comment]
Hi!
I encountered the same error with balancing pool router, switching to another type helped.
My error messages were slightly different, with very strange first error:
```
[ERROR] [05/24/2015 03:06:06.406] [NastarDownloader-akka.actor.default-dispatcher-4] [akka://NastarDownloader/user/downloader-main] received Supervise from unregistered child Actor[akka://NastarDownloader/user/downloader-main/sftp-router#-2120128525], this will not end well
[ERROR] [05/24/2015 03:06:06.408] [NastarDownloader-akka.actor.default-dispatcher-5] [akka://NastarDownloader/user/downloader-main] configuration problem while creating [akka://NastarDownloader/user/downloader-main/sftp-router] with router dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox] and routee dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox]
akka.actor.ActorInitializationException: exception during creation
  at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
  at akka.actor.ActorCell.create(ActorCell.scala:596)
  at akka.actor.ActorCell.invokeAll$1_aroundBody2(ActorCell.scala:456)
  at akka.actor.ActorCell$AjcClosure3.run(ActorCell.scala:1)
  at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
  at akka.kamon.instrumentation.ActorSystemMessageInstrumentation$$anonfun$aroundSystemMessageInvoke$1.apply(ActorSystemMessageInstrumentation.scala:34)
  at kamon.trace.Tracer$.withContext(TracerModule.scala:57)
  at akka.kamon.instrumentation.ActorSystemMessageInstrumentation.aroundSystemMessageInvoke(ActorSystemMessageInstrumentation.scala:34)
  at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:1)
  at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
  at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
  at akka.dispatch.Mailbox.run(Mailbox.scala:219)
  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: akka.ConfigurationException: configuration problem while creating [akka://NastarDownloader/user/downloader-main/sftp-router] with router dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox] and routee dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox]
  at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:753)
  at akka.actor.dungeon.Children$class.makeChild(Children.scala:206)
  at akka.actor.dungeon.Children$class.actorOf(Children.scala:37)
  at akka.actor.ActorCell.actorOf(ActorCell.scala:369)
  at ru.megafon.datalabs.nastar.downloader.actors.DownloaderMain.<init>(DownloaderMain.scala:31)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
  at java.lang.Class.newInstance(Class.java:438)
  at akka.util.Reflect$.instantiate(Reflect.scala:45)
  at akka.actor.NoArgsReflectConstructor.produce(Props.scala:361)
  at akka.actor.Props.newActor(Props.scala:252)
  at akka.actor.ActorCell.newActor(ActorCell.scala:552)
  at akka.actor.ActorCell.create(ActorCell.scala:578)
  ... 15 more
Caused by: java.lang.NullPointerException
  at akka.kamon.instrumentation.DispatcherInstrumentation.afterCreateExecutorService(DispatcherInstrumentation.scala:101)
  at akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory.createExecutorService(AbstractDispatcher.scala:424)
  at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor$lzycompute(Dispatcher.scala:44)
  at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor(Dispatcher.scala:44)
  at akka.dispatch.ExecutorServiceDelegate$class.execute(ThreadPoolBuilder.scala:212)
  at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:43)
  at akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:118)
  at akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:132)
  at akka.actor.dungeon.Dispatch$class.start(Dispatch.scala:87)
  at akka.actor.ActorCell.start(ActorCell.scala:369)
  at akka.actor.LocalActorRef.start(ActorRef.scala:321)
  at akka.actor.dungeon.Children$class.makeChild(Children.scala:220)
  at akka.actor.dungeon.Children$class.actorOf(Children.scala:35)
  at akka.actor.ActorCell.actorOf(ActorCell.scala:369)
  at akka.routing.BalancingPool.newRoutee(Balancing.scala:121)
  at akka.routing.RoutedActorCell$$anonfun$start$3.apply(RoutedActorCell.scala:116)
  at akka.routing.RoutedActorCell$$anonfun$start$3.apply(RoutedActorCell.scala:116)
  at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
  at akka.routing.RoutedActorCell.start(RoutedActorCell.scala:116)
  at akka.routing.RoutedActorCell.start(RoutedActorCell.scala:41)
  at akka.actor.RepointableActorRef.point_aroundBody0(RepointableActorRef.scala:105)
  at akka.actor.RepointableActorRef$AjcClosure1.run(RepointableActorRef.scala:1)
  at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
  at akka.kamon.instrumentation.TraceContextIntoRepointableActorRefMixin$$anonfun$afterRepointableActorRefCreation$1.apply(ActorSystemMessageInstrumentation.scala:77)
  at kamon.trace.Tracer$.withContext(TracerModule.scala:57)
  at akka.kamon.instrumentation.TraceContextIntoRepointableActorRefMixin.afterRepointableActorRefCreation(ActorSystemMessageInstrumentation.scala:76)
  at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:94)
  at akka.actor.RepointableActorRef.initialize(RepointableActorRef.scala:82)
  at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:751)
  ... 29 more
```
Hope it'll help in fixing the issue.
