### ISSUE TITLE
HdrHistogram OutOfBoundsException

### ISSUE THREAD

**Issue by jamesmulcahy** [kamon-io/Kamon#211]
Running 0.3.6-a2840a7020df81056a656d3e88be223f7af62ac6 (which is essentially a 0.4.0 pre-release).

We see this exception after startup, and repeating at 1s intervals throughout the lifecycle of the Application.  We don't see this across all instances, but it has occurred on one instances we brought up yesterday.

[ERROR] [06/01/2015 15:55:42.995] [kamon-akka.actor.default-dispatcher-9] [akka://kamon/user/kamon-system-metrics/sigar-metrics-recorder] value outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 4841
java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 4841
at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:428)
at org.HdrHistogram.AbstractHistogram.recordCountAtValue(AbstractHistogram.java:407)
at org.HdrHistogram.AbstractHistogram.recordValueWithCount(AbstractHistogram.java:344)
at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:117)
at kamon.system.sigar.DiffRecordingHistogram.processRecording(DiffRecordingHistogram.scala:37)
at kamon.system.sigar.DiffRecordingHistogram.record(DiffRecordingHistogram.scala:45)
at kamon.system.sigar.FileSystemMetrics.update(FileSystemMetrics.scala:41)
at kamon.system.sigar.SigarMetricsUpdater.updateMetrics(SigarMetricsUpdater.scala:47)
at kamon.system.sigar.SigarMetricsUpdater$$anonfun$receive$1.applyOrElse(SigarMetricsUpdater.scala:42)
at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
at kamon.system.sigar.SigarMetricsUpdater.aroundReceive(SigarMetricsUpdater.scala:28)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487)
at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at akka.kamon.instrumentation.ActorCellInstrumentation$$anonfun$aroundBehaviourInvoke$1.apply(ActorCellInstrumentation.scala:62)
at kamon.trace.Tracer$.withContext(TracerModule.scala:57)
at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:61)
at akka.actor.ActorCell.invoke(ActorCell.scala:483)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
at akka.dispatch.Mailbox.run(Mailbox.scala:221)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)

**Comment by dpsoft** [comment]
the damon system-metrics module was redesigned in 0.4.0 we will assume that this error was fixed.
