### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNativeVersion()Ljava/lang/String

### ISSUE THREAD

**Issue by mirkof** [kamon-io/Kamon#283]
Hello :)

I'm getting this error every second time I start sbt.
This happens when I run tests. 
Not sure why is this happening...

The stacktrace:
```
[INFO] [11/09/2015 15:20:58.483] [pool-5-thread-3] [SystemMetricsExtension(akka://kamon)] Starting the Kamon(SystemMetrics) extension
Nov 09, 2015 3:20:58 PM kamon.sigar.SigarProvisioner provision
WARNING: Sigar library is already provisioned.
[ERROR] [11/09/2015 15:20:58.533] [kamon-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(kamon)] Uncaught error from thread [kamon-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNativeVersion()Ljava/lang/String;
        at org.hyperic.sigar.Sigar.getNativeVersion(Native Method)
        at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:101)
        at kamon.system.custom.ContextSwitchesMetrics$.register(ContextSwitchesMetrics.scala:92)
        at kamon.system.SystemMetricsSupervisor.<init>(SystemMetricsExtension.scala:73)
        at kamon.system.SystemMetricsSupervisor$$anonfun$props$1.apply(SystemMetricsExtension.scala:90)
        at kamon.system.SystemMetricsSupervisor$$anonfun$props$1.apply(SystemMetricsExtension.scala:90)
        at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:339)
        at akka.actor.Props.newActor(Props.scala:259)
        at akka.actor.ActorCell.newActor(ActorCell.scala:561)
        at akka.actor.ActorCell.create(ActorCell.scala:587)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:460)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:482)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by mirkof** [comment]
Sigar is trying to read system metrics while you are testing. 
In our case, we "disabled" Kamon for unit and integration tests. because these metrics we can ignore.
we created `application.test.conf` included default `application.conf` and overwritten Kamon settings with these: 
```
kamon {
  show-aspectj-missing-warning = no
  metric.disable-aspectj-weaver-missing-error = true

  modules {
    kamon-statsd {
      auto-start = no
      extension-id = "kamon.statsd.StatsD"
    }

    kamon-system-metrics {
      auto-start = no
      extension-id = "kamon.system.SystemMetrics"
    }
    kamon-play {
      auto-start = no
      extension-id = "kamon.play.Play"
    }
    kamon-akka {
      auto-start = no
      extension-id = "kamon.akka.Akka"
    }
  }
}
```

I hope this helps! :)

**Comment by dpsoft** [comment]
@mirkof thanks for sharing!!!

**Comment by caoilte** [comment]
This may be out of date now. I just had to set,

```
{
kamon.system-metrics.host.enabled = false
}
```

See,
https://github.com/kamon-io/kamon-system-metrics
