### ISSUE TITLE
Histogram recorded value cannot be negative in ProcessCpuMetrics

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#291]
[ERROR] [11/12/2015 10:39:26.403] [kamon-akka.actor.default-dispatcher-8] [akka://kamon/user/kamon-system-metrics/sigar-metrics-recorder] Histogram recorded value cannot be negative.
java.lang.ArrayIndexOutOfBoundsException: Histogram recorded value cannot be negative.
    at org.HdrHistogram.AbstractHistogram.countsArrayIndex(AbstractHistogram.java:2068)
    at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:427)
    at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:346)
    at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:115)
    at kamon.system.sigar.ProcessCpuMetrics.update(ProcessCpuMetrics.scala:69)
    at kamon.system.sigar.SigarMetricsUpdater.updateMetrics(SigarMetricsUpdater.scala:49)

**Comment by dpsoft** [comment]
Looking at the code of ProcessCpuMetrics it seems to me that in fact there can occur negative numbers:
``` scala
def update(): Unit = {
    val currentProcCpu = sigar.getProcCpu(pid)
    val totalDiff = currentProcCpu.getTotal - lastProcCpu.getTotal
    val userDiff = currentProcCpu.getUser - lastProcCpu.getUser
    val systemDiff = currentProcCpu.getSys - lastProcCpu.getSys
    val timeDiff = currentProcCpu.getLastTime - lastProcCpu.getLastTime

    def percentUsage(delta: Long): Long = Try(100 * delta / timeDiff / totalCores).getOrElse(0L)

    if (totalDiff == 0) {
      if (timeDiff > 2000) currentLoad = 0
      if (currentLoad == 0) lastProcCpu = currentProcCpu
    } else {
      val totalPercent = percentUsage(totalDiff)
      val userPercent = percentUsage(userDiff)
      val systemPercent = percentUsage(systemDiff)

      processUserCpu.record(userPercent)
      processSystemCpu.record(systemPercent)   // <<<==== this is line 69
      processTotalCpu.record(userPercent + systemPercent)

      currentLoad = totalPercent
      lastProcCpu = currentProcCpu
    }
  }
```
