### ISSUE TITLE
Kamon StackOverflowError shutting down JVM

### ISSUE THREAD

**Issue by ShakhoVW** [kamon-io/Kamon#295]
Hi! Can somebody help me with this Kamon error:

```
[ERROR] [12/01/2015 19:09:44.697] [kamon-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(kamon)] Uncaught error from thread [kamon-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.StackOverflowError
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3776)
        at java.util.regex.Pattern$Curly.match0(Pattern.java:4250)
        at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
        at java.util.regex.Matcher.match(Matcher.java:1270)
        at java.util.regex.Matcher.matches(Matcher.java:604)
        at kamon.util.GlobPathFilter.accept(GlobPathFilter.java:51)
        at kamon.metric.SubscriptionFilter$$anon$3.accept(SubscriptionsDispatcher.scala:113)
        at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
        at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
        at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
        at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
        at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
...
```
My config:

```
kamon {
  disable = false
  akka {
    ask-pattern-timeout-warning = off
  }

  metric {
    tick-interval = 2 second
    filters {
      akka-actor {
        includes = ["**"]
        excludes = ["*/system/**", "*/user/IO-**"]
      }

      akka-dispatcher {
        includes = ["*"]
        excludes = []
      }
    }
  }

  riemann {
    hostname = "riemann"
    port = 5555

    subscriptions {
      trace           = ["**"]
      akka-actor      = ["**"]
      akka-dispatcher = ["**"]
      akka-router     = ["**"]
      counter         = ["**"]
      min-max-counter = ["**"]
      histogram       = ["**"]
      gauge           = ["**"]
      system-metric   = ["**"]
    }
  }

  modules {
    kamon-riemann {
      auto-start = yes
      requires-aspectj = no
      extension-id = "RiemannReporter"
    }
    kamon-akka {
      auto-start = yes
      requires-aspectj = yes
      extension-id = "kamon.akka.Akka"
    }
    kamon-system-metrics {
      auto-start: yes
      requires-aspectj: no
      extension-id: "kamon.system.SystemMetrics"
    }
  }
}
```

This is actor wrapper to send custom metrics to Riemann
Deps:
```
  val kamonVersion = "0.4.0"
  val kamonCore = "io.kamon" %% "kamon-core" % kamonVersion % Provided
  val kamonScala = "io.kamon" %% "kamon-scala" % kamonVersion % Provided
  val kamonAkka = "io.kamon" %% "kamon-akka" % kamonVersion
  val kamonSM = "io.kamon" %% "kamon-system-metrics" % kamonVersion
```
PS: I know about jvm-exit-on-fatal-error = off option, but I need a solution to avoid this error

**Comment by dpsoft** [comment]
@ShakhoVW you can change the kamon version to  0.5.2 and check if the error persist?

**Comment by ShakhoVW** [comment]
@dpsoft Thanks, I'll try
"kamon-riemann" - Kamon extension for collect & send metrics to riemann.io

**Comment by dpsoft** [comment]
@ShakhoVW cool!!  private repo?

**Comment by ShakhoVW** [comment]
@dpsoft yeah, but I might share it
btw load test hasn't fallen with exception above

**Comment by dpsoft** [comment]
@ShakhoVW They are planning to open to the community? I think that can be really usefull. @thjaeckle are you interested?
