### ISSUE TITLE
Match error with auto-start=false

### ISSUE THREAD

**Issue by trobert** [kamon-io/Kamon#300]
(On branch java8)
Kamon crash when I start with the following config `kamon. modules.kamon-system-metrics.auto-start = false`

```
17:44:24.985 [main] INFO  Kamon - Initializing Kamon...
17:44:24.992 [main] INFO  Kamon - Trying to load kamon-autoweave...
17:44:24.994 [main] INFO  Kamon - Kamon-autoweave failed to load. Reason: we have not found the kamon.autoweave.Autoweave$ class in the classpath.
17:44:26.993 [main] DEBUG kamon.ModuleLoaderExtension - Auto starting the [kamon-log-reporter] module.
[INFO] [01/08/2016 17:44:26.999] [main] [LogReporterExtension(akka://kamon)] Starting the Kamon(LogReporter) extension
17:44:27.026 [main] DEBUG kamon.ModuleLoaderExtension - Auto starting the [kamon-statsd] module.
[INFO] [01/08/2016 17:44:27.030] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
Exception in thread "main" scala.MatchError: AvailableModuleInfo(kamon-system-metrics,false,Some(ModuleStartInfo(false,kamon.system.SystemMetrics))) (of class kamon.AvailableModuleInfo)
	at kamon.ModuleLoaderExtension.<init>(ModuleLoader.scala:38)
	at kamon.ModuleLoader$.createExtension(ModuleLoader.scala:27)
	at kamon.ModuleLoader$.createExtension(ModuleLoader.scala:25)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
	at kamon.Kamon$._start$lzycompute(Kamon.scala:52)
	at kamon.Kamon$._start(Kamon.scala:49)
	at kamon.Kamon$.start(Kamon.scala:55)

```

**Comment by dpsoft** [comment]
related to #302
