### ISSUE TITLE
Play 2.5 support (especially for websockets)

### ISSUE THREAD

**Issue by an-tex** [kamon-io/Kamon#340]
When using Play 2.5 with the kamon play integration and aspectj, there's an issue if there are any actions using the new stream based websockets. On startup the following exception is thrown and kills the application:

```
[error] - play.core.server.netty.PlayRequestHandler - Exception caught in Netty
java.lang.ClassCastException: play.api.libs.streams.DoneAccumulator cannot be cast to play.api.libs.iteratee.Iteratee
	at kamon.play.instrumentation.RequestInstrumentation$$anon$1$$anonfun$apply$1.apply(RequestInstrumentation.scala:60) ~[io.kamon.kamon-play-24_2.11-0.6.0.jar:0.6.0]
	at kamon.play.instrumentation.RequestInstrumentation$$anon$1$$anonfun$apply$1.apply(RequestInstrumentation.scala:46) ~[io.kamon.kamon-play-24_2.11-0.6.0.jar:0.6.0]
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:62) ~[com.typesafe.play.play_2.11-2.5.1.jar:2.5.1]
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:61) ~[com.typesafe.play.play_2.11-2.5.1.jar:2.5.1]
	at play.core.server.netty.PlayRequestHandler$$anonfun$2.apply(PlayRequestHandler.scala:98) ~[com.typesafe.play.play-netty-server_2.11-2.5.1.jar:2.5.1]
	at play.core.server.netty.PlayRequestHandler$$anonfun$2.apply(PlayRequestHandler.scala:96) ~[com.typesafe.play.play-netty-server_2.11-2.5.1.jar:2.5.1]
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:62) ~[com.typesafe.play.play_2.11-2.5.1.jar:2.5.1]
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:61) ~[com.typesafe.play.play_2.11-2.5.1.jar:2.5.1]
	at play.core.server.netty.PlayRequestHandler.play$core$server$netty$PlayRequestHandler$$handleAction(PlayRequestHandler.scala:243) ~[com.typesafe.play.play-netty-server_2.11-2.5.1.jar:2.5.1]
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:102) ~[com.typesafe.play.play-netty-server_2.11-2.5.1.jar:2.5.1]
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:162) ~[com.typesafe.play.play-netty-server_2.11-2.5.1.jar:2.5.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129) [com.typesafe.netty.netty-reactive-streams-http-1.0.5.jar:na]
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96) [com.typesafe.netty.netty-reactive-streams-http-1.0.5.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [io.netty.netty-codec-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) [io.netty.netty-codec-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) [io.netty.netty-codec-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [io.netty.netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [io.netty.netty-common-4.0.34.Final.jar:4.0.34.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
```

Websocket with streams example: https://www.playframework.com/documentation/2.5.x/ScalaWebSockets#Handling-WebSockets-with-Akka-Streams-and-actors

**Comment by dpsoft** [comment]
@an-tex currently kamon doesn't support play 2.5, but thanks to @dspasojevic you can take a look here:
https://github.com/agiledigital/kamon-play-2.5.x

**Comment by ezhulkov** [comment]
@dpsoft Diego, hi!
Do you have any estimate of when it is done?

**Comment by dpsoft** [comment]
@ezhulkov we are waiting the @dspasojevic pull request ;)

**Comment by dpsoft** [comment]
related to https://github.com/kamon-io/Kamon/pull/362

**Comment by folex** [comment]
I have similar problem, don't know if it's Kamon causing it. 
Using `0.6.2` kamon and tried play `2.5.2` and `2.5.8`, I'm always getting this error:
```
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
java.lang.ClassCastException: play.api.libs.iteratee.FutureIteratee cannot be cast to play.api.libs.streams.Accumulator
	at play.api.mvc.BodyParser$$anon$8.apply(Action.scala:258)
	at play.api.mvc.BodyParser$$anon$8.apply(Action.scala:257)
	at play.api.mvc.Action$class.apply(Action.scala:103)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:455)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:455)
	at play.core.routing.TaggingInvoker$$anon$2.apply(HandlerInvoker.scala:44)
	at play.core.routing.TaggingInvoker$$anon$2.apply(HandlerInvoker.scala:43)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2.apply(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2.apply(PlayRequestHandler.scala:97)
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:62)
```
Stacktrace doesn't show any links to my code, I think it happens on Play sbt plugin loading.
