### ISSUE TITLE
NullPointerException during creation of actor system

### ISSUE THREAD

**Issue by kurbatov** [kamon-io/Kamon#341]
I'm trying to introduce kamon into my project to monitor an actor system.
I added kamon-core and kamon-akka to the dependencies. After that, when the application starts, it fails with the following exception:

```
java.lang.NullPointerException: null
    at akka.kamon.instrumentation.DispatcherInstrumentation.afterCreateExecutorService(DispatcherInstrumentation.scala:115)
    at akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory.createExecutorService(AbstractDispatcher.scala:432)
    at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor$lzycompute(Dispatcher.scala:40)
    at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor(Dispatcher.scala:40)
    at akka.dispatch.ExecutorServiceDelegate$class.execute(ThreadPoolBuilder.scala:209)
    at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:39)
    at akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:115)
    at akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:131)
    at akka.actor.dungeon.Dispatch$class.start(Dispatch.scala:99)
    at akka.actor.ActorCell.start(ActorCell.scala:374)
    at akka.actor.LocalActorRef.start(ActorRef.scala:341)
    at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:661)
    at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:666)
    at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:663)
    at akka.actor.ActorSystemImpl._start(ActorSystem.scala:663)
    at akka.actor.ActorSystemImpl.start(ActorSystem.scala:679)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:108)
    at akka.actor.ActorSystem$.create(ActorSystem.scala:56)
    at akka.actor.ActorSystem.create(ActorSystem.scala)
```

I tried with akka 2.3.14, 2.4.2, 2.43.3 and kamon 0.5.2 and 0.6.0 getting the same error.

I provide no custom configuration for akka nor for kamon.

Reading sources of akka and kamon did not clarify the issue for me. Could somebody tell me what am I missing?

**Comment by dpsoft** [comment]
@kurbatov you can share with us an simple example in order to reproduce this weird issue?

**Comment by kurbatov** [comment]
I set up [a project](https://github.com/kurbatov/kamon-test) to illustrate my use-case. Use `mvn test` to run it.

Basicly the NPE happens when actor system is created by spring like this:

```xml
<bean id="actorSystem" class="akka.actor.ActorSystem" factory-method="create" destroy-method="shutdown" scope="singleton">
    <constructor-arg value="TestingActorSystem"/>
</bean>
```
([see in the project](https://github.com/kurbatov/kamon-test/blob/master/src/main/webapp/WEB-INF/context.xml))

However invokation of the same factory method in the constructor of a spring-bean or in post-construct method works fine:

```java
@Component
public class ActorSystemHolder {
    private ActorSystem actorSystem;
    public ActorSystemHolder() {
        // works
        actorSystem = ActorSystem.create("ConstructorTestActorSystem");
    }
    @PostConstruct
    public void init() {
        // works
        actorSystem = ActorSystem.create("PostConstructTestActorSystem");
    }
}
```
([see in the project](https://github.com/kurbatov/kamon-test/blob/master/src/main/java/kamon/test/ActorSystemHolder.java))

For now I'm fine to move initialization of the actor system into a spring-bean but curious what's going wrong when I describe creation of the actor system in spring xml configuration.

**Comment by matlik** [comment]
If I were to venture a guess, this issue is the result of loading Kamon's autoweave feature after the application's ActorSystem has been initialized.  I ran into this exact same issue using Scala, Akka 2.4.4 and no DI framework.  Once I moved the startup of Kamon before the creation of my ActorSystem, the NPE errors went away.

I don't know if there are plans to make this "just work".  If not, I think it would be be reasonable to:
1.  generate a meaningful error message suggesting there may be a startup order issue.
2. fall back to a pass-through behavior to remain functioning without metrics.

**Comment by dpsoft** [comment]
@matlik I think that issue above is not the same as you, but agree with you with the meaningful error message.Maybe ```This offers extra flexibility but obviously any classes loaded before attachment will not be woven.```

**Comment by dpsoft** [comment]
@matlik I've added a meaningful [message] in the startup. thanks for you feedback.

[message]: https://github.com/kamon-io/Kamon/blob/bda51ea175d734025bf36abb0f8678a5d1c0959d/kamon-core/src/main/scala/kamon/Kamon.scala#L73

**Comment by dpsoft** [comment]
@kurbatov sorry for the late response :(. I found that if you run the example with:

```markup 
<argLine>-javaagent:/path/to/aspectjweaver.jar</argLine>
```
and remove from `context.xml`:
```
    <context:load-time-weaver/>
```
the example runs fine:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
SUREFIRE-859: [AppClassLoader@14dad5dc] info AspectJ Weaver Version 1.8.7 built on Wednesday Sep 9, 2015 at 21:19:30 GMT
[AppClassLoader@14dad5dc] info register classloader sun.misc.Launcher$AppClassLoader@14dad5dc
[AppClassLoader@14dad5dc] info using configuration /home/diego/gitHub/kamon-test/target/classes/META-INF/aop.xml
[AppClassLoader@14dad5dc] info using configuration file:/home/diego/.m2/repository/org/springframework/spring-aspects/4.2.5.RELEASE/spring-aspects-4.2.5.RELEASE.jar!/META-INF/aop.xml
[AppClassLoader@14dad5dc] info using configuration file:/home/diego/.m2/repository/io/kamon/kamon-core_2.11/0.6.2/kamon-core_2.11-0.6.2.jar!/META-INF/aop.xml
[AppClassLoader@14dad5dc] info using configuration file:/home/diego/.m2/repository/io/kamon/kamon-akka_2.11/0.6.2/kamon-akka_2.11-0.6.2.jar!/META-INF/aop.xml
[AppClassLoader@14dad5dc] info using configuration file:/home/diego/.m2/repository/io/kamon/kamon-scala_2.11/0.6.2/kamon-scala_2.11-0.6.2.jar!/META-INF/aop.xml
[AppClassLoader@14dad5dc] info register aspect org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect
[AppClassLoader@14dad5dc] info register aspect org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspect
[AppClassLoader@14dad5dc] info register aspect org.springframework.transaction.aspectj.AnnotationTransactionAspect
[AppClassLoader@14dad5dc] info register aspect org.springframework.transaction.aspectj.JtaAnnotationTransactionAspect
[AppClassLoader@14dad5dc] info deactivating aspect 'org.springframework.transaction.aspectj.JtaAnnotationTransactionAspect' as it requires type 'javax.transaction.Transactional' which cannot be found on the classpath
[AppClassLoader@14dad5dc] info register aspect org.springframework.cache.aspectj.AnnotationCacheAspect
[AppClassLoader@14dad5dc] info register aspect org.springframework.cache.aspectj.JCacheCacheAspect
[AppClassLoader@14dad5dc] info deactivating aspect 'org.springframework.cache.aspectj.JCacheCacheAspect' as it requires type 'javax.cache.annotation.CacheResult' which cannot be found on the classpath
[AppClassLoader@14dad5dc] info register aspect kamon.AspectJPresent
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.TraceContextIntoRepointableActorRefMixin
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.TraceContextIntoSystemMessageMixin
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.ActorSystemMessageInstrumentation
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.EnvelopeContextIntoEnvelopeMixin
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.MetricsIntoActorCellsMixin
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.MetricsIntoRouterCellsMixin
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.ActorCellInstrumentation
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.RoutedActorCellInstrumentation
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.ActorLoggingInstrumentation
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.DispatcherInstrumentation
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.DispatcherMetricCollectionInfoIntoDispatcherMixin
[AppClassLoader@14dad5dc] info register aspect akka.kamon.instrumentation.AskPatternInstrumentation
[AppClassLoader@14dad5dc] info register aspect kamon.scala.instrumentation.FutureInstrumentation
[AppClassLoader@14dad5dc] info register aspect kamon.scalaz.instrumentation.FutureInstrumentation
[AppClassLoader@14dad5dc] info register aspect kamon.twitter.instrumentation.FutureInstrumentation
Running TestSuite
...
... TestNG 6.8.9beta by Cédric Beust (cedric@beust.com)
...

2016-08-22 23:00:35 INFO  [main] DefaultTestContextBootstrapper:207 - Could not instantiate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [javax/servlet/ServletContext]
2016-08-22 23:00:35 INFO  [main] DefaultTestContextBootstrapper:185 - Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@6c61a903, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@658c5a19, org.springframework.test.context.support.DirtiesContextTestExecutionListener@421e361]
2016-08-22 23:00:35 INFO  [main] XmlBeanDefinitionReader:317 - Loading XML bean definitions from URL [file:src/main/webapp/WEB-INF/context.xml]
2016-08-22 23:00:35 INFO  [main] GenericApplicationContext:578 - Refreshing org.springframework.context.support.GenericApplicationContext@43b9fd5: startup date [Mon Aug 22 23:00:35 ART 2016]; root of context hierarchy
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.351 sec - in TestSuite
2016-08-22 23:00:45 INFO  [Thread-1] GenericApplicationContext:960 - Closing org.springframework.context.support.GenericApplicationContext@43b9fd5: startup date [Mon Aug 22 23:00:35 ART 2016]; root of context hierarchy

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.382s
[INFO] Finished at: Mon Aug 22 23:00:45 ART 2016
[INFO] Final Memory: 9M/147M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0

```
we need investigate a little more but, this sounds like the `spring-instrument`,   `<context:load-time-weaver/>`
 and friends are guilty of the issue :).

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
