### ISSUE TITLE
Trace contexts cause NoSuchMethodErrors errors in Akka Clusters

### ISSUE THREAD

**Issue by DomBlack** [kamon-io/Kamon#348]
We are using Kamon 0.6.1. 
We created a new context in one node, the code path then used and `ask` to talk to another node, that other node immediately crashed out (due to `akka.jvm-exit-on-fatal-error`) because Kamon had tried to call an unknown method:

```
[INFO] [05/03/2016 11:31:10.509] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[INFO] [05/03/2016 11:31:10.548] [main] [SystemMetricsExtension(akka://kamon)] Starting the Kamon(SystemMetrics) extension
Uncaught error from thread [octopus-akka.remote.default-remote-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[octopus]
java.lang.NoSuchMethodError: kamon.trace.TracerModuleImpl.newContext(Ljava/lang/String;Lscala/Option;JZZ)Lkamon/trace/TraceContext;
        at akka.kamon.instrumentation.RemotingInstrumentation.aroundDecodeRemoteMessage(RemotingInstrumentation.scala:89)
        at akka.remote.transport.AkkaPduProtobufCodec$.decodeMessage(AkkaPduCodec.scala:181)
        at akka.remote.EndpointReader.akka$remote$EndpointReader$$tryDecodeMessageAndAck(Endpoint.scala:1028)
        at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:960)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:439)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:495)
        at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at akka.kamon.instrumentation.ActorMonitors$$anon$1$$anonfun$processMessage$1.apply(ActorMonitor.scala:59)
        at kamon.trace.Tracer$.withContext(TracerModule.scala:57)
        at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:58)
        at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:44)
        at akka.actor.ActorCell.invoke(ActorCell.scala:488)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
#### Dependencies File

``` scala
  object Version {
    val Scala       = "2.11.8"
    val Akka        = "2.4.4"
    val Kamon       = "0.6.1"
  }

  val kamonCore            = "io.kamon"                   %% "kamon-core"                    % Version.Kamon

  val kamonStatsd          = "io.kamon"                   %% "kamon-statsd"                  % Version.Kamon
  val kamonNewRelic        = "io.kamon"                   %% "kamon-newrelic"                % Version.Kamon
  val kamonLogReporter     = "io.kamon"                   %% "kamon-log-reporter"            % Version.Kamon

  val kamonAnnotation      = "io.kamon"                   %% "kamon-annotation"              % Version.Kamon
  val kamonScala           = "io.kamon"                   %% "kamon-scala"                   % Version.Kamon
  val kamonAkka            = "io.kamon"                   %% "kamon-akka"                    % Version.Kamon
  val kamonAkkaRemote      = "io.kamon"                   %% "kamon-akka-remote_akka-2.4"    % Version.Kamon
  val kamonSystemMetrics   = "io.kamon"                   %% "kamon-system-metrics"          % Version.Kamon
```

**Comment by DomBlack** [comment]
We've traced the error down.

The published 0.6.1's akka-2.4 is missing this line (the Map.empty):
https://github.com/kamon-io/Kamon/blob/v0.6.1/kamon-akka-remote/src/main/scala/kamon/akka/instrumentation/RemotingInstrumentation.scala#L92

Can you publish 0.6.2 with a fixed line?

**Comment by dpsoft** [comment]
@DomBlack we've just published a snapshot version with this fix please add our repo ```"Kamon Repository Snapshots" at "http://snapshots.kamon.io"``` and the artifact is: ```0.6.2-b10b1cf2013460c791d5e3f7600fc654145f3d4e```

**Comment by 2m** [comment]
Thanks for the snapshot. It fixed the same problem I was having.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
