### ISSUE TITLE
Monitoring akka dispatcher broken for akka 2.4.7

### ISSUE THREAD

**Issue by danischroeter** [kamon-io/Kamon#374]
We try to use kamon 2.6.1 with akka 2.4.7 (akka with remote,clustering,http)

When we enable monitoring with kamon and configure some dispatchers to be monitored we get
```
[info]  11:14:52.457UTC 2016-07-15T11:14:52.457Z ERROR |bank|a.actor.OneForOneStrategy|akka://mysys/user/StreamSupervisor-0|bank-akka.actor.default-dispatcher-34 cannot enqueue after timer shutdown
[info]  java.lang.IllegalStateException: cannot enqueue after timer shutdown
[info]  at akka.actor.LightArrayRevolverScheduler.schedule(LightArrayRevolverScheduler.scala:132)
[info]  at akka.actor.Scheduler$class.schedule(Scheduler.scala:78)
[info]  at akka.actor.LightArrayRevolverScheduler.schedule(LightArrayRevolverScheduler.scala:37)
[info]  at kamon.metric.instrument.DefaultRefreshScheduler.schedule(RefreshScheduler.scala:36)
[info]  at kamon.metric.instrument.LazyRefreshScheduler.schedule(RefreshScheduler.scala:60)
[info]  at kamon.metric.instrument.Gauge$.apply(Gauge.scala:40)
[info]  at kamon.metric.instrument.InstrumentFactory.createGauge(InstrumentFactory.scala:47)
[info]  at kamon.metric.GenericEntityRecorder$$anonfun$gauge$1.apply(EntityRecorder.scala:169)
[info]  at kamon.metric.GenericEntityRecorder$$anonfun$gauge$1.apply(EntityRecorder.scala:169)
[info]  at kamon.util.TriemapAtomicGetOrElseUpdate$Syntax$.atomicGetOrElseUpdate$extension1(TriemapAtomicGetOrElseUpdate.scala:35)
```
(tested on osx and linux)

If we configure kamon not to monitor any dispatcher the system works (so far).

# Kamon config
```
kamon {
  metric {
    filters {
      akka-actor {
        includes = [ "mysys/user/*-singletonMgr/**", "mysys/user/*Service/**"]
        excludes = [ "*/system/**", "*/user/IO-**" ]
      }
      akka-dispatcher {
        includes = [ "bank/akka.actor.default-dispatcher","bank/akka.remote.default-remote-dispatcher", "bank/akka.stream.default-blocking-io-dispatcher"]
      }
    }

    tick-interval = 10 second
  }
```

# Startup Log
```
[error] objc[37385]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[info]   INFO  ||TestUi$|| using in memory persistence
[info]    INFO  ||TestUi$|| enable monitoring with kamon
[info]    INFO  ||Kamon|| Initializing Kamon...
[info]    INFO  ||Kamon|| Trying to load kamon-autoweave...
[info]    DEBUG ||Kamon|| Kamon-autoweave failed to load. Reason: null.
[info]    DEBUG ||k.ModuleLoaderExtension|| Auto starting the [kamon-fluentd] module.
[info]  [INFO] [07/15/2016 13:22:36.377] [main] [FluentdExtension(akka://kamon)] Starting the Kamon(Fluentd) extension
[info]   DEBUG ||k.ModuleLoaderExtension|| Auto starting the [kamon-system-metrics] module.
[info]  [INFO] [07/15/2016 13:22:36.407] [main] [SystemMetricsExtension(akka://kamon)] Starting the Kamon(SystemMetrics) extension
[error] Jul 15, 2016 1:22:36 PM kamon.sigar.SigarProvisioner provision
[error] INFO: Sigar library provisioned: /Users/xxx/git/xxx/xxx/native/libsigar-universal64-macosx.dylib
```
I found out that 'Kamon-autoweave failed to load. Reason: null.' is considered ok

# Dependencies
```
  lazy val akkaDeps = Seq(
    "com.typesafe.akka" %% "akka-actor" % akkaV,
    "com.typesafe.akka" %% "akka-slf4j" % akkaV,
    "com.typesafe.akka" %% "akka-persistence-cassandra" % "0.16",
    "com.typesafe.akka" %% "akka-testkit" % akkaV % Test,
    "com.typesafe.akka" %% "akka-cluster" % akkaV,
    "com.typesafe.akka" %% "akka-cluster-sharding" % akkaV,
    "com.typesafe.akka" %% "akka-contrib" % akkaV,
    "com.google.protobuf" % "protobuf-java" % "2.6.1",
    "com.google.guava" % "guava" % "18.0"
  )

lazy val kamonDeps = Seq(
  "io.kamon" %% "kamon-core" % kamonV exclude("com.typesafe.akka", "akka-actor_2.11"),
  "io.kamon" %% "kamon-fluentd" % kamonV exclude("com.typesafe.akka", "akka-actor_2.11") exclude("org.fluentd","fluent-logger"),
  "io.kamon" %% "kamon-system-metrics" % kamonV excludeAll(ExclusionRule("log4j", "log4j"), ExclusionRule("com.typesafe.akka", "akka-actor_2.11")),
  "io.kamon" %% "kamon-scala" % kamonV,
  "io.kamon" %% "kamon-akka" % kamonV exclude("com.typesafe.akka", "akka-actor_2.11"),
  "io.kamon" %% "kamon-akka-remote_akka-2.4" % kamonV excludeAll(ExclusionRule("com.typesafe.akka", "akka-actor_2.11"), ExclusionRule("com.typesafe.akka", "akka-cluster_2.11"), ExclusionRule("com.typesafe.akka", "akka-remote_2.11"))
)
```

**Comment by ivantopo** [comment]
hello @danischroeter, given the error message there it seems like if Kamon was shutdown while the application was still running, does it seem possible to you?

**Comment by danischroeter** [comment]
good point - right the kamon internal actor system was stopped - actually some other failure caused our app to shutdown Kamon.
Thx
