### ISSUE TITLE
Kamon breaks 'import' in conf file

### ISSUE THREAD

**Issue by mulya** [kamon-io/Kamon#375]
My applicaton.conf looks like that
```
import "akka"

http {
  interface = "0.0.0.0"
  port = 9000
}
```

akka.conf contains akka actors configuration and everything works fine. But when I start Kamon i see error: 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.zina.filezmeta.Boot$.delayedEndpoint$com$zina$filezmeta$Boot$1(Boot.scala:16)
	at com.zina.filezmeta.Boot$delayedInit$body.apply(Boot.scala:12)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.zina.filezmeta.Boot$.main(Boot.scala:12)
	at com.zina.filezmeta.Boot.main(Boot.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: akka.ConfigurationException: Dispatcher [akka.actor.cacheEc] not configured
	at akka.dispatch.Dispatchers.lookupConfigurator(Dispatchers.scala:99)
	at akka.dispatch.Dispatchers.lookup_aroundBody0(Dispatchers.scala:81)
	at akka.dispatch.Dispatchers$AjcClosure1.run(Dispatchers.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at akka.kamon.instrumentation.DispatcherInstrumentation$$anonfun$aroundDispatchersLookup$1.apply(DispatcherInstrumentation.scala:96)
	at akka.kamon.instrumentation.LookupDataAware$.withLookupData(DispatcherInstrumentation.scala:206)
	at akka.kamon.instrumentation.DispatcherInstrumentation.aroundDispatchersLookup(DispatcherInstrumentation.scala:95)
	at akka.dispatch.Dispatchers.lookup(Dispatchers.scala:81)
	at com.zina.filezmeta.core.ComponentRegistry$components$.<init>(ComponentRegistry.scala:59)
	at com.zina.filezmeta.core.ComponentRegistry$components$.<clinit>(ComponentRegistry.scala)
	... 16 more
```
Looks like Kamon doesn't handle "import" properly.

**Comment by mulya** [comment]
My bad, 'clean' fixed this problem.
