### ISSUE TITLE
Upgrade from 0.5.1 to 0.5.2 results in AskTimeoutException

### ISSUE THREAD

**Issue by nickebbitt** [kamon-io/Kamon#405]
Hello,

We've been using Kamon for a while and all working great however simply upgrading to the latest version causes problems our the app. 

The app is Spring based with Spring MVC REST controllers in which we create a DeferredResult and pass it to an Akka actor for async processing using ActorSelection#resolveOne. The processing actor has a large timeout of 30 seconds which is triggering.

We are using load time weaving with `aspectjweaver-1.8.4.jar`.

Here's a few examples errors from the Tomcat log:

```
14-Oct-2016 17:10:50.949 SEVERE [http-nio-9003-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [DispatcherServlet] in context with path [/resource-server] threw exception [Request processing failed; nested exception is akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://camp/user/$c#-219495918]] after [30000 ms]. Sender[null] sent message of type "uk.co.datasys.camp.common.actor.config.CoreActorType$1".] with root cause
 akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://camp/user/$c#-219495918]] after [30000 ms]. Sender[null] sent message of type "uk.co.datasys.camp.common.actor.config.CoreActorType$1".
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
    at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
    at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
    at java.lang.Thread.run(Thread.java:745)

14-Oct-2016 17:11:21.041 SEVERE [http-nio-9003-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [DispatcherServlet] in context with path [/resource-server] threw exception [Request processing failed; nested exception is akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://camp/user/$d#-603600427]] after [30000 ms]. Sender[null] sent message of type "uk.co.datasys.camp.common.actor.config.CoreActorType$1".] with root cause
 akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://camp/user/$d#-603600427]] after [30000 ms]. Sender[null] sent message of type "uk.co.datasys.camp.common.actor.config.CoreActorType$1".
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
    at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
    at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
    at java.lang.Thread.run(Thread.java:745)

14-Oct-2016 17:11:51.100 SEVERE [http-nio-9003-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [DispatcherServlet] in context with path [/resource-server] threw exception [Request processing failed; nested exception is akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://camp/user/$e#2139811360]] after [30000 ms]. Sender[null] sent message of type "uk.co.datasys.camp.common.actor.config.CoreActorType$1".] with root cause
 akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://camp/user/$e#2139811360]] after [30000 ms]. Sender[null] sent message of type "uk.co.datasys.camp.common.actor.config.CoreActorType$1".
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
    at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
    at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
    at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
    at java.lang.Thread.run(Thread.java:745)

```

Not sure if the above is helpful, please advise if there's any additional info that will help diagnose the problem.

Thanks

**Comment by nickebbitt** [comment]
A further check based on v0.6.0 and the the same problem occurs.

**Comment by nickebbitt** [comment]
Further testing shows that the problem actually occurs from simply upgrading from 0.5.1 to 0.5.2 so hopefully this helps focus in on the issue.

**Comment by dpsoft** [comment]
hey @nickebbitt I've found that the only change related to akka between versions is https://github.com/kamon-io/Kamon/blob/v0.5.2/project/Dependencies.scala#L26

**Comment by ivantopo** [comment]
hey @nickebbitt! So, to see if I understand this correctly, after upgrading to Kamon > 0.5.2 the ask pattern is not working nicely for you? like if messages were not being delivered and you start seeing timeouts?

**Comment by nickebbitt** [comment]
Hi @ivantopo, that is correct..summarises the problem we're having nicely

**Comment by ivantopo** [comment]
@nickebbitt could you please tell us exactly what akka version are you running?

**Comment by nickebbitt** [comment]
@ivantopo yes

```
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-actor_2.11</artifactId>
            <version>2.4.10</version>
            <type>jar</type>
        </dependency>
```

Based on the link @dpsoft provided we have a version mismatch - could this be where our problem lies?

**Comment by nickebbitt** [comment]
I will experiment with the Akka version in the next day or so to see if aligning it fixes our issue

**Comment by nickebbitt** [comment]
@ivantopo we've had time to investigate this further and our findings are that when we downgrade our Akka version to 2.3.14 as per Kamon's dependency the problem goes away.

There seems to be some incompatibility between the current Kamon version based on Akka 2.3.14 and Akka 2.4.x.

Have you tested Kamon against Akka 2.4 yet? I may be oversimplifying things but is it as straightforward as bumping the Akka version in the Dependencies.scala file?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
