### ISSUE TITLE
Kamon 0.6.5 won't start with Play 2.5

### ISSUE THREAD

**Issue by osbornk** [kamon-io/Kamon#428]
I was running my Play 2.5 application fine with Kamon 0.6.3 and the aspectj-play-runner 0.1.4 plugin.

Here are my steps:

```
activator -jvm-debug 9999 -J-Dhttp.port=9002
aspectj-runner:run -Dconfig.file=conf/application.conf -Dkamon.auto-start=true
```

I then get the following stack trace after a couple seconds.

```
java.lang.Exception: Kamon.start() not called yet
	at kamon.Kamon$.config(Kamon.scala:70)
	at kamon.Kamon$.metrics$lzycompute(Kamon.scala:72)
	at kamon.Kamon$.metrics(Kamon.scala:72)
	at akka.kamon.instrumentation.LookupDataAware$LookupData$.apply$default$3(DispatcherInstrumentation.scala:196)
	at akka.kamon.instrumentation.DispatcherInstrumentation.aroundDispatchersLookup(DispatcherInstrumentation.scala:95)
	at akka.dispatch.Dispatchers.lookup(Dispatchers.scala:79)
	at akka.dispatch.Dispatchers.defaultGlobalDispatcher(Dispatchers.scala:69)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:634)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:226)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:65)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:64)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:54)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

I am running with the following dependencies:

kamon-akka 0.6.3
kamon-core 0.6.3
kamon-log-reporter 0.6.3
kamon-play-25 0.6.3
kamon-system-metrics 0.6.3
aspectjweaver 1.8.10

As soon as I boost kamon-core to 0.6.4 or 0.6.5, I get the exception. Perhaps because kamon-play-25 is not compiled against kamon-core 0.6.5?

**Comment by dpsoft** [comment]
@osbornk I think that we have introduced a bug in 0.6.5, can you please add ```resolvers += "Kamon Repository Snapshots"  at "http://snapshots.kamon.io"``` and  only change `kamon-core` to `0.6.6-SNAPSHOT`?

**Comment by oskoi** [comment]
@osbornk I have the same problem. Everything became working after replacing the 0.6.5 to 0.6.6-SNAPSHOT version. When to expect release with fix?

**Comment by ivantopo** [comment]
I will try to publish at some point this week :)

**Comment by osbornk** [comment]
So  I updated kamon-core and that problem went away. But now I get a second error once Play starts.

```
play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

I see similar errors when several of my custom modules startup. They don't do much except startup a couple actors.

It looks like ScalaForkJoin used to be an object inside kamon.util.executors.ForkJoinPools. But now it got moved inside the trait ForkJoinLowPriority.

Perhaps because kamon-akka or kamon-play-25 are still on 0.6.3?

1) Error injecting method, java.lang.NoClassDefFoundError: kamon/util/executors/ForkJoinPools$ScalaForkJoin$
  at com.google.inject.util.Providers$GuicifiedProviderWithDependencies.initialize(Providers.java:149)
  at play.api.libs.concurrent.AkkaGuiceSupport$class.bindActor(Akka.scala:139) (via modules: com.google.inject.util.Modules$OverrideModule -> com.centraldesktop.edge.infrastructure.play.modules.GlobalActorsModule)
Caused by: java.lang.NoClassDefFoundError: kamon/util/executors/ForkJoinPools$ScalaForkJoin$
	at akka.kamon.instrumentation.DispatcherInstrumentation.registerDispatcher(DispatcherInstrumentation.scala:79)
	at akka.kamon.instrumentation.DispatcherInstrumentation.afterActorSystemInitialization(DispatcherInstrumentation.scala:52)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:670)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:126)
	at play.api.libs.concurrent.ActorSystemProvider$.start(Akka.scala:300)
	at play.api.libs.concurrent.ActorSystemProvider.get$lzycompute(Akka.scala:257)
	at play.api.libs.concurrent.ActorSystemProvider.get(Akka.scala:256)
	at play.api.libs.concurrent.ActorSystemProvider.get(Akka.scala:252)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:984)
	at com.google.inject.util.Providers$GuicifiedProviderWithDependencies.initialize(Providers.java:149)
	at com.google.inject.util.Providers$GuicifiedProviderWithDependencies$$FastClassByGuice$$2a7177aa.invoke(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastMethod.invoke(FastMethod.java:53)
	at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:57)
	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:91)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:174)
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:108)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:168)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:164)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:164)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:131)
	at scala.Option.map(Option.scala:146)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:131)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:129)
	at scala.util.Success.flatMap(Try.scala:231)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:129)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:121)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run_aroundBody0(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable$AjcClosure1.run(Future.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:45)
	at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:44)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: kamon.util.executors.ForkJoinPools$ScalaForkJoin$
	at org.aspectj.weaver.bcel.ExtensibleURLClassLoader.findClass(ExtensibleURLClassLoader.java:54)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 64 more
```

**Comment by ivantopo** [comment]
that might be! I'm working on release kamon-play with the new versions of core and akka, so far I'm integrating it in a Play 2.4 application, will try out 2.5 right after that! ping you later with results :)

**Comment by osbornk** [comment]
Thanks. If you want me to try it on Play 2.5 once you have a SNAPSHOT tag, let me know.

**Comment by ivantopo** [comment]
we just published kamon-core 0.6.6 on Bintray, add this to your build to get access to it: `resolvers += Resolver.bintrayRepo("kamon-io", "releases")`

we are requesting artifacts to be synced to jcentar and maven central, but it seems like it will take longer than expected to get set up :/, now I'm going to try Play 2.5

**Comment by ivantopo** [comment]
so, the very latest versions of everything are working fine with Play 2.5, I'm going to release this on bintray shortly :D

**Comment by ivantopo** [comment]
@osbornk we just released `kamon-play-2.5` on our bintray repo: https://bintray.com/kamon-io/releases/kamon-play-2.5/0.6.5

I tested it and it's working nicely! We also released a new version of the sbt-aspectj-play-runner (1.0.0) that also works nicely with Play 2.5 and everything easier with Play, more info here: https://github.com/kamon-io/sbt-aspectj-runner

I'm closing the issue as everything should be fixed when using the new versions, otherwise please reopen, thanks!

**Comment by osbornk** [comment]
Thanks for your help. I will do some more testing later, but everything seems to be working perfectly. I especially like the new sbt-play-aspectj-runner. Makes it much easier to just do "run". Great work.

**Comment by ivantopo** [comment]
thanks a lot! we are also happy that things are getting simpler :smile:, enjoy the release!
