### ISSUE TITLE
Kamon - Akka -  Java  - InstrumentedEnvelope not serializable

### ISSUE THREAD

**Issue by pawelciesielka** [kamon-io/Kamon#457]
Hi,
we have a problem while creating persistent mailbox.

While akka.kamon.instrumentation.InstrumentedEnvelope is not serializable  and we can't persist EnvelopeContext so we persist just envelope - but after unpersisting envelope  we have NullPointerException in        (AkkaMonitor.scala(58) -> Tracer.withContext(envelopeContext.context) 
 because  EnvelopeContext is null.

Is there a way to persist envelope with envelopeContext, or apply new context while unpersisting envelope with message?

Here is the exception:
```
java.lang.NullPointerException: null
 at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:58)
 at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:44)
 at akka.actor.ActorCell.invoke(ActorCell.scala:488)
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
 at akka.dispatch.Mailbox.run(Mailbox.scala:224)
 at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
 at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by pjfanning** [comment]
@pawelciesielka would you be able to write a test case to demonstrate your issue?

**Comment by pawelciesielka** [comment]
@pjfanning thanks for answer I will move it to https://github.com/kamon-io/kamon-akka

**Comment by pawelciesielka** [comment]
I have attached code to test this issue and moved the it to  https://github.com/kamon-io/kamon-akka/issues/13  but there is no response. This issue is caused by kamon context serialization problems - so I decided to reopen it here.

**Comment by dpsoft** [comment]
@pawelciesielka fixed with https://github.com/kamon-io/kamon-akka/pull/14
