### ISSUE TITLE
upgrading kamon-akka dependency on kamon-core to 0.6.7 breaks kamon-akka-2.3 unit tests

### ISSUE THREAD

**Issue by pjfanning** [kamon-io/Kamon#461]
Seems that this change is akka 2.4 specific
https://github.com/kamon-io/Kamon/commit/dc7f240540b468ab68b99011d7fa587207a98609

The provider="local" causes the kamon-akka-2.3 unit tests to fail.

One example:
                     <testcase classname="kamon.instrumentation.akka.ActorSystemMessageInstrumentationSpec" name="(It is not a test)" time="0.003">
                                                 <error message="java.lang.ClassNotFoundException: local" type="sbt.ForkMain$ForkError">sbt.ForkMain$ForkError: java.lang.ClassNotFoundException: local
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:67)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:66)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(DynamicAccess.scala:66)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
	at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:585)
	at akka.actor.ActorSystemImpl.&lt;init&gt;(ActorSystem.scala:578)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at kamon.Kamon$Instance._start$lzycompute(Kamon.scala:61)
	at kamon.Kamon$Instance._start(Kamon.scala:58)
	at kamon.Kamon$Instance.start(Kamon.scala:69)
	at kamon.Kamon$.start(Kamon.scala:37)
	at kamon.testkit.BaseKamonSpec.system$lzycompute(BaseKamonSpec.scala:31)
	at kamon.testkit.BaseKamonSpec.system(BaseKamonSpec.scala:30)

**Comment by pjfanning** [comment]
http://doc.akka.io/docs/akka/2.3.16/scala/remoting.html
http://doc.akka.io/docs/akka/2.4.18/scala/remoting.html

Note the way the provider value changed from a class name to local/remote between akka 2.3 and 2.4

**Comment by pjfanning** [comment]
http://doc.akka.io/docs/akka/current/general/configuration.html says
    # Either one of "local", "remote" or "cluster" or the
    # FQCN of the ActorRefProvider to be used; the below is the built-in default,
    # note that "remote" and "cluster" requires the akka-remote and akka-cluster
    # artifacts to be on the classpath.
    provider = "local"

For akka 2.3 compatibility it is best to use the FQCN
