### ISSUE TITLE
JMX MX export requires key-property "name"

### ISSUE THREAD

**Issue by drobert** [kamon-io/Kamon#466]
(Originally opened in the kamon-jmx project: https://github.com/kamon-io/kamon-jmx/issues/2 but the traction seems to be in this general kamon issue tracker).

I'm using kamon 2.6 along with the kamon-jmx module (using scala 2.12) and I'm exporting metrics from MX Beans. I recently added [Hikari DBCP](https://github.com/brettwooldridge/HikariCP)'s MXBean data as part of this export and have been seeing NPEs in the logs. 

Hikari's MXBeans follows this naming convention: `com.zaxxer.hikari:type=Pool (POOLNAME)`. Note that there is a 'type', but no 'name'.

This appears to be an issue in `kamon.jmx.extension.ExportedMBeanQuery`'s `rebuildRecorders()`, in particular in this line: `name.getKeyProperty("name")`.  This value comes back `null` and ultimately results in the case class `Entity` being instantiated with a null name, which causes problems during filtering and subscription management.

I think there are a few issues here:
1) Configuration looks to allow for a 'name' value but it does not seem to be used. Instead the hard-coded key property is assumed.
2) There should be a means of excluding entities without valid names without dropping the full metrics group on the floor (perhaps being able to filter on 'null')
3) Is the 'name' property in configuration actually used? The documentation is very unclear here and it anecdotally does not seem to be.

However, I've opened this ticket specifically to address that some mx beans cannot be exported due to a lack of a "key property" called "name".

Relevant configuration:
```scala
kamon-mxbeans {
    mbeans = [
      { "name": "hikari", "jmxQuery": "com.zaxxer.hikari:type=Pool (postgres)",
        "attributes": [
          {"name": "ActiveConnections", "type": "min_max_counter"},
          {"name": "IdleConnections", "type": "min_max_counter"},
          {"name": "ThreadsAwaitingConnection", "type": "min_max_counter"},
          {"name": "TotalConnections", "type": "min_max_counter"}
        ]
      }
    ],
```

Full stack trace here:

```
[ERROR] [06/06/2017 17:32:24.806] [kamon-akka.actor.default-dispatcher-6] [akka://kamon/user/metrics] null
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at kamon.util.GlobPathFilter.accept(GlobPathFilter.java:51)
	at kamon.metric.SubscriptionFilter$$anon$3.accept(SubscriptionsDispatcher.scala:113)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionFilter$$anon$2.accept(SubscriptionsDispatcher.scala:99)
	at kamon.metric.SubscriptionsDispatcher.$anonfun$dispatchSelections$3(SubscriptionsDispatcher.scala:75)
	at kamon.metric.SubscriptionsDispatcher.$anonfun$dispatchSelections$3$adapted(SubscriptionsDispatcher.scala:75)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at kamon.metric.SubscriptionsDispatcher.$anonfun$dispatchSelections$2(SubscriptionsDispatcher.scala:75)
	at kamon.metric.SubscriptionsDispatcher.$anonfun$dispatchSelections$2$adapted(SubscriptionsDispatcher.scala:74)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at kamon.metric.SubscriptionsDispatcher.dispatchSelections(SubscriptionsDispatcher.scala:74)
	at kamon.metric.SubscriptionsDispatcher.dispatch(SubscriptionsDispatcher.scala:64)
	at kamon.metric.SubscriptionsDispatcher.processTick(SubscriptionsDispatcher.scala:42)
	at kamon.metric.SubscriptionsDispatcher$$anonfun$receive$1.applyOrElse(SubscriptionsDispatcher.scala:35)
	at akka.actor.Actor.aroundReceive(Actor.scala:497)
	at akka.actor.Actor.aroundReceive$(Actor.scala:495)
	at kamon.metric.SubscriptionsDispatcher.aroundReceive(SubscriptionsDispatcher.scala:27)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:495)
	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at akka.kamon.instrumentation.ActorMonitors$$anon$1.$anonfun$processMessage$1(ActorMonitor.scala:59)
	at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
	at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:59)
	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:45)
	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
