### ISSUE TITLE
Unable to export MBean value as gauge in scala

### ISSUE THREAD

**Issue by drobert** [kamon-io/Kamon#467]
I'm using Kamon 0.6.6 with Scala 2.12 using the kamon-jmx module for exporting mbean values. As near as I can tell, it is not possible to export jmx values via a 'gauge' instrument.

There are a few issues:
1. The documentation lists the supported attributes types as: "counter, guage, min_max_counter and histogram" <-- notice 'gauge' is mis-spelled. The value "gauge" works.
2. A gauge cannot be created without a refresh interval, which is missing from the configuration docs and examples.
3. There does not seem to be a means of specifying a gauge refresh interval in the mxbean export config syntax that doesn't result in a ClassCastException.

Example configurations:

```
  kamon-mxbeans {
    mbeans = [
      { "name": "slick", "jmxQuery": "slick:type=AsyncExecutor,name=*",
        "attributes": [
          {"name": "ActiveThreads", "type": "gauge"},
          {"name": "QueueSize", "type": "gauge"}
        ]
      }
    ]
```
The above does not work as it's missing a refresh interval.

```
  kamon-mxbeans {
    mbeans = [
      { "name": "slick", "jmxQuery": "slick:type=AsyncExecutor,name=*",
        "attributes": [
          {"name": "ActiveThreads", "type": "gauge", "interval": "100"},
          {"name": "QueueSize", "type": "gauge", "interval": "100"}
        ]
      }
    ]
```

The above does not work as the interval value is expected to be a Long not a String

```
  kamon-mxbeans {
    mbeans = [
      { "name": "slick", "jmxQuery": "slick:type=AsyncExecutor,name=*",
        "attributes": [
          {"name": "ActiveThreads", "type": "gauge", "interval": 100L},
          {"name": "QueueSize", "type": "gauge", "interval": 100L}
        ]
      }
    ]
```
The above fails as '100L' is interpreted as a String rather than a Long (unsurprising).

```
  kamon-mxbeans {
    mbeans = [
      { "name": "slick", "jmxQuery": "slick:type=AsyncExecutor,name=*",
        "attributes": [
          {"name": "ActiveThreads", "type": "gauge", "interval": 100},
          {"name": "QueueSize", "type": "gauge", "interval": 100}
        ]
      }
    ]
```

This one fails as there is a cast from `java.lang.Integer` to `java.lang.Long` with this stack trace:
```
[ERROR] [06/08/2017 11:05:59.917] [kamon-akka.actor.default-dispatcher-4] [TaskInvocation] java.lang.Integer cannot be cast to java.lang.Long
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at scala.runtime.BoxesRunTime.unboxToLong(BoxesRunTime.java:105)
	at kamon.jmx.extension.MetricDefinition$.getFiniteDuration(MetricDefinition.scala:88)
	at kamon.jmx.extension.MetricDefinition.<init>(MetricDefinition.scala:126)
	at kamon.jmx.extension.ExportedMBeanQuery.$anonfun$rebuildRecorders$5(ExportedMBeanQuery.scala:201)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kamon.jmx.extension.ExportedMBeanQuery.$anonfun$rebuildRecorders$3(ExportedMBeanQuery.scala:195)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at kamon.jmx.extension.ExportedMBeanQuery.rebuildRecorders(ExportedMBeanQuery.scala:188)
	at kamon.jmx.extension.ExportedMBeanQuery$$anon$2.run(ExportedMBeanQuery.scala:229)
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:102)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The underlying line of code resulting in this stack trace is in `kamon.jmx.extension.MetricDefinition` in method `getFiniteDuration`:
```scala
  def getFiniteDuration(
    metricConfig: Map[String, Any]): Option[FiniteDuration] =

    if (metricConfig.contains("interval")) {
      val millis: Long = metricConfig("interval").asInstanceOf[Long]
      Some(new FiniteDuration(millis, TimeUnit.MILLISECONDS))
    } else {
      None
    }
```

Looking at the above: `asInstanceOf[Long]` is not a safe means of doing numeric type conversion in scala. I believe this should be `metricConfig("interval").toLong`. That said, a safe conversion directly from String to Long would be helpful as well such that "100L", "100", "100 ms", etc. could be specified as the refresh interval.

**Comment by dpsoft** [comment]
@drobert PR? ;)

**Comment by drobert** [comment]
Step one was to open the issue for visibility to others. If someone gets to this before me great, if not I'll try to put something together soon.
