### ISSUE TITLE
NPE on startup when upgraded to akka 2.5.3

### ISSUE THREAD

**Issue by xuweigui** [kamon-io/Kamon#481]
It was working fine with akka 2.4.2. 
After I upgraded to akka 2.5. 
I always get this kind of NPE during startup.

12:09:43,806  INFO DEVPortalCluster-akka.actor.default-dispatcher-2 remote.Remoting:108 - Starting remoting
12:09:43,881 ERROR DEVPortalCluster-akka.actor.default-dispatcher-3 actor.ActorSystemImpl:161 - Uncaught error from thread [DEVPortalCluster-akka.actor.default-dispatcher-2]
java.lang.NullPointerException
        at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:58)
        at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:44)
        at akka.actor.ActorCell.invoke(ActorCell.scala:489)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by pjfanning** [comment]
Have you tried io.kamon:kamon-akka-2.5_2.12:0.6.7 ?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
