### ISSUE TITLE
akka.kamon.instrumentation.ActorLoggingInstrumentation -- (IllegalStateException) there is no classname for invokedynamic

### ISSUE THREAD

**Issue by cwei-bgl** [kamon-io/Kamon#496]
I am using akka 2.5.6, akka-http 10.0.10 and Kamon 0.6.7. Getting the follow errors, please help. Thanks.

```
---- Compiler Messages ---
info AspectJ Weaver Version 1.8.9 built on Monday Mar 14, 2016 at 21:18:16 GMT
info register classloader sun.misc.Launcher$AppClassLoader@14dad5dc

info using configuration file:/Users/.../lib/io.kamon.kamon-core_2.12-0.6.7.jar!/META-INF/aop.xml
info using configuration file:/Users/.../lib/io.kamon.kamon-akka-2.5_2.12-0.6.7.jar!/META-INF/aop.xml
info using configuration file:/Users/.../lib/io.kamon.kamon-scala_2.12-0.6.7.jar!/META-INF/aop.xml
info using configuration file:/Users/.../lib/io.kamon.kamon-akka-http_2.12-0.6.7.jar!/META-INF/aop.xml

abort trouble in: 
akka.kamon.instrumentation.ActorLoggingInstrumentation -- (IllegalStateException) there is no classname for invokedynamic
there is no classname for invokedynamic
java.lang.IllegalStateException: there is no classname for invokedynamic
	at org.aspectj.apache.bcel.generic.InvokeDynamic.getClassName(InvokeDynamic.java:126)
	at org.aspectj.weaver.bcel.BcelAccessForInlineMunger.openAroundAdvice(BcelAccessForInlineMunger.java:141)
	at org.aspectj.weaver.bcel.BcelAccessForInlineMunger.munge(BcelAccessForInlineMunger.java:80)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:440)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:100)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1697)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1641)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1406)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1159)
	at org.aspectj.weaver.tools.WeavingAdaptor.getWovenBytes(WeavingAdaptor.java:527)
	at org.aspectj.weaver.tools.WeavingAdaptor.weaveClass(WeavingAdaptor.java:363)
	at org.aspectj.weaver.loadtime.Aj.preProcess(Aj.java:121)
	at org.aspectj.weaver.loadtime.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:54)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at akka.event.Logging$Debug.<init>(Logging.scala:809)
	at akka.event.LoggingBus.startStdoutLogger(Logging.scala:93)
	at akka.event.LoggingBus.startStdoutLogger$(Logging.scala:91)
	at akka.event.EventStream.startStdoutLogger(EventStream.scala:23)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:740)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:244)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:287)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:262)
	at kamon.Kamon$Instance._start$lzycompute(Kamon.scala:61)
	at kamon.Kamon$Instance._start(Kamon.scala:58)
	at kamon.Kamon$Instance.start(Kamon.scala:74)
	at kamon.Kamon$.start(Kamon.scala:41)
```

**Comment by dpsoft** [comment]
Hi @cwei-bgl, I think that this issues is related to : `https://bugs.eclipse.org/bugs/show_bug.cgi?id=490315`, can you please try run with `aspectjweaver.jar` >= `1.8.10`

**Comment by cwei-bgl** [comment]
Thanks @dpsoft. You are right. It is working now.
