### ISSUE TITLE
UnknownHostException thrown in Kamon.init

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#531]
The Kamon initialization could throw a `UnknownHostException` in certain cases where no DNS nor `hosts` entry is found for the container. Thanks @nilsga for reporting it!

More info here: https://gitter.im/kamon-io/Kamon?at=5af1676803cafa797b35e906

**Comment by nilsga** [comment]
Stacktrace:

Caused by: java.net.UnknownHostException: 41f08e5dff44: 41f08e5dff44: Name or service not known

at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
at kamon.Environment$.$anonfun$fromConfig$2(Environment.scala:37)
at kamon.Environment$.readValueOrGenerate(Environment.scala:49)
at kamon.Environment$.fromConfig(Environment.scala:37)
at kamon.Kamon$.<init>(Kamon.scala:36)
at kamon.Kamon$.<clinit>(Kamon.scala)
... 11 more
Caused by: java.net.UnknownHostException: 41f08e5dff44: Name or service not known
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
... 16 more

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
