### ISSUE TITLE
Can't use Kamon if there is a configuration typo

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#564]
Something like this is shown when there is a configuration error during Kamon initialization process:

```
Dec 24 19:10:40 xxxx java[123]: 2018-12-24T19:10:40.543 main INFO  AppStateManager transitioned to 'Initializing' (caused by: agent-service-init-started)
Dec 24 19:10:41 xxxx java[123]: Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class kamon.Kamon$
Dec 24 19:10:41 dxxxx java[123]:         at kamon.context.HasContext$.fromCurrentContext(Mixin.scala:44)
Dec 24 19:10:41 xxxx java[123]:         at kamon.scala.instrumentation.FutureInstrumentation.mixinTraceContextAwareToFutureRelatedRunnable(FutureInstrumentation.scala:29)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.CallbackRunnable.context(Promise.scala:1)
Dec 24 19:10:41 xxxx java[123]:         at kamon.scala.instrumentation.FutureInstrumentation.afterCreation(FutureInstrumentation.scala:37)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.CallbackRunnable.<init>(Promise.scala:54)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.Promise.transform(Promise.scala:29)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.Future.map(Future.scala:287)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.Future.map$(Future.scala:287)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
Dec 24 19:10:41 xxxx java[123]:         at scala.concurrent.Future$.apply(Future.scala:653)
```

As mentioned on [Gitter](https://gitter.im/kamon-io/Kamon?at=5c2132953c4093612c57d406), this can be caused by a simple configuration typo like a missing comma. I would suggest this flow:
  1. Load the configuration as usual, if it succeeds then continue as usual.
  2. If loading config fails, fallback to loading the default reference, show a warning log with the cause and continue with the default reference.
  3. If loading the default reference fails, show an error message with the actual cause and let it fail.

**Comment by ivantopo** [comment]
This issue is fixed on Kamon 1.1.6 and also already fixed for the Kamon 2.0 release.
