### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range.

### ISSUE THREAD

**Issue by REASY** [kamon-io/Kamon#575]
I recieved the following exception:
```
08:37:53.462 [main] WARN  kamon.metric.instrument.HdrHistogram - Failed to store value 4925967814879 in HdrHistogram, please review your range configuration.
java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 4623
        at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:492)
        at org.HdrHistogram.AbstractHistogram.recordCountAtValue(AbstractHistogram.java:471)
        at org.HdrHistogram.AbstractHistogram.recordValueWithCount(AbstractHistogram.java:408)
        at kamon.metric.instrument.HdrHistogram.tryRecord(Histogram.scala:160)
        at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:154)
        at kamon.trace.MetricsOnlyContext.finish(MetricsOnlyContext.scala:68)
        at kamon.trace.MetricsOnlyContext.finish(MetricsOnlyContext.scala:74)
        at beam.sim.metrics.MetricsSupport.stopMeasuring(MetricsSupport.scala:69)
        at beam.sim.metrics.MetricsSupport.stopMeasuring$(MetricsSupport.scala:67)
        at beam.sim.BeamSim.stopMeasuring(BeamSim.scala:43)
        at beam.sim.metrics.MetricsSupport.stopMeasuringIteration(MetricsSupport.scala:58)
        at beam.sim.metrics.MetricsSupport.stopMeasuringIteration$(MetricsSupport.scala:58)
        at beam.sim.BeamSim.stopMeasuringIteration(BeamSim.scala:43)
        at beam.sim.BeamSim.notifyIterationEnds(BeamSim.scala:209)
        at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerIterationEndsEvent(ControlerListenerManagerImpl.java:168)
        at org.matsim.core.controler.AbstractController$5.run(AbstractController.java:161)
        at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
        at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:157)
        at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
```

Dependencies (`gradle`):
```
def kamonVersion = "0.6.7"
compile("io.kamon:kamon-core_${scalaBinaryVersion}:${kamonVersion}")
compile("io.kamon:kamon-scala_${scalaBinaryVersion}:${kamonVersion}")
compile("io.kamon:kamon-akka-2.4_${scalaBinaryVersion}:${kamonVersion}")
compile("io.kamon:kamon-statsd_${scalaBinaryVersion}:${kamonVersion}")
compile "io.kamon:kamon-influxdb_${scalaBinaryVersion}:0.6.9"
compile("io.kamon:kamon-log-reporter_${scalaBinaryVersion}:${kamonVersion}")
```

**Comment by ppgf135** [comment]
what is the solution

**Comment by Philippus** [comment]
https://github.com/kamon-io/Kamon/issues/284#issuecomment-198669928

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
