### ISSUE TITLE
NPE when logging warnings through logback

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#634]
When Kamon's initialization needs to log a warning and the Logback instrumentation is present a NPE is thrown because the Logback instrumentation is trying to read Kamon's config before it gets fully initialized. Stack trace:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at kamon.instrumentation.logback.GetPropertyMapMethodInterceptor$.aroundGetMDCPropertyMap(LogbackInstrumentation.scala:92)
    at ch.qos.logback.classic.util.LogbackMDCAdapter.getPropertyMap(LogbackMDCAdapter.java)
    at ch.qos.logback.classic.spi.LoggingEvent.getMDCPropertyMap(LoggingEvent.java:306)
    at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:209)
    at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
    at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
    at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
    at ch.qos.logback.classic.Logger.warn(Logger.java:692)
    at kamon.Configuration.loadInitialConfiguration(Configuration.scala:75)
    at kamon.Configuration.$init$(Configuration.scala:27)
    at kamon.Kamon$.<init>(Kamon.scala:19)
    at kamon.Kamon$.<clinit>(Kamon.scala)
    at io.otrl.fare_finder.infrastructure.MainApp$.run(MainApp.scala:86)
    at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:67)
    at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:37)
    at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:24)
    at cats.effect.IOApp.main(IOApp.scala:67)
    at cats.effect.IOApp.main$(IOApp.scala:66)
    at io.otrl.fare_finder.infrastructure.MainApp$.main(MainApp.scala:74)
    at io.otrl.fare_finder.infrastructure.MainApp.main(MainApp.scala)
Caused by: java.lang.NullPointerException
    at kamon.instrumentation.logback.LogbackInstrumentation$.readSettings(LogbackInstrumentation.scala:65)
    at kamon.instrumentation.logback.LogbackInstrumentation$.<init>(LogbackInstrumentation.scala:50)
    at kamon.instrumentation.logback.LogbackInstrumentation$.<clinit>(LogbackInstrumentation.scala)
    ... 25 more
```

Reported by @IgorCandido on [Gitter](https://gitter.im/kamon-io/Kamon?at=5e3c021f6f9d3d349824748c)

**Comment by jatcwang** [comment]
I encountered this issue too.

**Comment by Reeebuuk** [comment]
Us too
