### ISSUE TITLE
instrumentation fails with mocked objects in tests

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#648]
This was reported by @jalaziz on [gitter](https://gitter.im/kamon-io/Kamon?at=5d5c50032a8af02b5fe11c98):

> I'm seeing something weird. When I run unti tests with an object that's mocked (but the implemenation uses a static logger), I'm getting the following exception:

```
Caused by: sbt.ForkMain$ForkError: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.<clinit>(AppenderAttachableImpl.java:112)
    ... 73 more
Caused by: sbt.ForkMain$ForkError: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at kanela.agent.libs.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:137)
    ... 77 more
Caused by: sbt.ForkMain$ForkError: java.lang.IllegalArgumentException: Can not set static kamon.instrumentation.logback.AppendLoopMethodInterceptor$ field ch.qos.logback.core.spi.AppenderAttachableImpl.delegate$u0i5811 to kamon.instrumentation.logback.AppendLoopMethodInterceptor$
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:81)
    at java.lang.reflect.Field.set(Field.java:764)
    at kanela.agent.libs.net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:124)
    at kanela.agent.libs.net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:187)
    at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3146)
    ... 82 more
```

#### Possible workaround:
Add `kanela.modules.logback.enabled=false` to the test configurations.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
