### ISSUE TITLE
Instrumented hikari pool should not throw when encountering a non-instrumented jdbc jar

### ISSUE THREAD

**Issue by alvaroc1** [kamon-io/Kamon#658]
Here is a stacktrace for H2 driver:
```
[error] c.z.h.p.HikariPool - HikariPool-2 - Error thrown while acquiring connection from data source
java.lang.ClassCastException: org.h2.jdbc.JdbcConnection cannot be cast to kamon.instrumentation.jdbc.HasConnectionPoolTelemetry
    at kamon.instrumentation.jdbc.PoolBaseNewConnectionAdvice$.enter(HikariInstrumentation.scala:194)
    at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:387)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:355)
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
    at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

Also for mysql connectorj 8.0 driver (same trace):
```
java.lang.ClassCastException: com.mysql.cj.jdbc.ConnectionImpl cannot be cast to kamon.instrumentation.jdbc.HasConnectionPoolTelemetry
```

I created this PR for mysql and redshift, but the code should probably be fixed so it just warns instead of throwing:
https://github.com/kamon-io/kamon-jdbc/pull/22

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
