### ISSUE TITLE
Can't load custom SlowStatementProcessor

### ISSUE THREAD

**Issue by yarosman** [kamon-io/Kamon#661]
If you try to create create custom SlowStatementProcessor, play application will not start.

Project for reproducing https://github.com/yarosman/kamon-play-anorm

```scala
[error] k.Configuration - Exception occurred while trying to run a OnReconfigureHook
java.lang.ClassNotFoundException: utils.CustomSlowStatementProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at kamon.instrumentation.sbt.KanelaOnSystemClassLoader.loadClass(KanelaOnSystemClassLoader.java:33)
	at kamon.instrumentation.sbt.play.SbtKanelaRunnerPlay$SbtKanelaClassLoader.loadClass(SbtKanelaRunnerPlay.scala:76)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at kamon.util.DynamicAccess.getClassFor(DynamicAccess.scala:37)
	at kamon.util.DynamicAccess.createInstanceFor(DynamicAccess.scala:60)
	at kamon.ClassLoading.createInstance(ClassLoading.scala:51)
```

@ivantopo Have you ever had such problem ?

**Comment by srouth-gloo** [comment]
I am getting a similar, but perhaps related, error for the provided custom logger kamon.instrumentation.jdbc.JdbcInstrumentation.LoggingProcessors.WarnOnSlowStatement. This seems to only occur when the HikariCP classloader is in play (connectionPool is enabled). Please let me know if I should open a separate issue for this.

```[postgresConf connection adder] ERROR 2020-03-30 15:20:45  Logger : An error occurred while trying to apply an advisor: java.lang.ExceptionInInitializerError
	at kamon.instrumentation.jdbc.StatementMonitor$Invocation.close(StatementMonitor.scala:79)
	at kamon.instrumentation.jdbc.advisor.PreparedStatementExecuteUpdateMethodAdvisor$.$anonfun$executeEnd$6(StatementInstrumentationAdvisors.scala:118)
	at kamon.instrumentation.jdbc.advisor.PreparedStatementExecuteUpdateMethodAdvisor$.$anonfun$executeEnd$6$adapted(StatementInstrumentationAdvisors.scala:118)
	at scala.Option.foreach(Option.scala:274)
	at kamon.instrumentation.jdbc.advisor.PreparedStatementExecuteUpdateMethodAdvisor$.executeEnd(StatementInstrumentationAdvisors.scala:118)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:126)
	at org.postgresql.jdbc.PgConnection.isValid(PgConnection.java:1383)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:454)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:421)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:374)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: kamon.instrumentation.jdbc.JdbcInstrumentation.LoggingProcessors.WarnOnSlowStatement
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at kamon.util.DynamicAccess.getClassFor(DynamicAccess.scala:37)
	at kamon.util.DynamicAccess.createInstanceFor(DynamicAccess.scala:60)
	at kamon.ClassLoading.createInstance(ClassLoading.scala:51)
	at kamon.ClassLoading.createInstance$(ClassLoading.scala:50)
	at kamon.ClassLoading$.createInstance(ClassLoading.scala:79)
	at kamon.instrumentation.jdbc.JdbcInstrumentation$.$anonfun$readSettings$1(JdbcInstrumentation.scala:71)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at kamon.instrumentation.jdbc.JdbcInstrumentation$.readSettings(JdbcInstrumentation.scala:71)
	at kamon.instrumentation.jdbc.JdbcInstrumentation$.<init>(JdbcInstrumentation.scala:14)
	at kamon.instrumentation.jdbc.JdbcInstrumentation$.<clinit>(JdbcInstrumentation.scala)
	at kamon.instrumentation.jdbc.StatementMonitor$Invocation.close(StatementMonitor.scala:79)
	at kamon.instrumentation.jdbc.advisor.PreparedStatementExecuteUpdateMethodAdvisor$.$anonfun$executeEnd$6(StatementInstrumentationAdvisors.scala:118)
	at kamon.instrumentation.jdbc.advisor.PreparedStatementExecuteUpdateMethodAdvisor$.$anonfun$executeEnd$6$adapted(StatementInstrumentationAdvisors.scala:118)
	at scala.Option.foreach(Option.scala:274)
	at kamon.instrumentation.jdbc.advisor.PreparedStatementExecuteUpdateMethodAdvisor$.executeEnd(StatementInstrumentationAdvisors.scala:118)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:126)
	at org.postgresql.jdbc.PgConnection.isValid(PgConnection.java:1383)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:454)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:421)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:374)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```
