### ISSUE TITLE
Message sent to an unstarted actor counted twice in actor_mailbox_size metric

### ISSUE THREAD

**Issue by kkamenev** [kamon-io/Kamon#670]
I'm using Kamon-Akka with Prometheus reporter. I noticed that mailbox size for some of my actors is 1 even though I was sure all messages were handled. After some debugging I figured out that it happens when I send a message to an actor right after getting an ActorRef from ActorSystem.actorOf(). Some more debugging showed that `akka.kamon.instrumentation.ActorCellInstrumentation#setEnvelopeContext` that eventually increments the mailbox size counter is called twice for the same message. See the stack traces below.

```
	at akka.kamon.instrumentation.ActorCellInstrumentation.setEnvelopeContext(ActorInstrumentation.scala:84)
	at akka.kamon.instrumentation.ActorCellInstrumentation.afterSendMessageInUnstartedActorCell(ActorInstrumentation.scala:80)
	at akka.actor.UnstartedCell.sendMessage(RepointableActorRef.scala:243)
	at akka.actor.Cell.sendMessage(ActorCell.scala:291)
	at akka.actor.Cell.sendMessage$(ActorCell.scala:290)
	at akka.actor.UnstartedCell.sendMessage(RepointableActorRef.scala:179)
	at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:171)
	at akka.actor.ActorRef.tell(ActorRef.scala:124)
```
```
	at akka.kamon.instrumentation.ActorCellInstrumentation.setEnvelopeContext(ActorInstrumentation.scala:84)
	at akka.kamon.instrumentation.ActorCellInstrumentation.afterSendMessageInActorCell(ActorInstrumentation.scala:74)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:370)
	at akka.actor.UnstartedCell.sendMessage(RepointableActorRef.scala:247)
	at akka.actor.Cell.sendMessage(ActorCell.scala:291)
	at akka.actor.Cell.sendMessage$(ActorCell.scala:290)
	at akka.actor.UnstartedCell.sendMessage(RepointableActorRef.scala:179)
	at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:171)
	at akka.actor.ActorRef.tell(ActorRef.scala:124)
```
Versions:
kamon-akka_2.5_2.12-1.0.0 (same issue with 1.0.2-SNAPSHOT)
akka-actor_2.12-2.5.8

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
