### ISSUE TITLE
ConfigException when running Play Application with an alternate config file

### ISSUE THREAD

**Issue by francjohny** [kamon-io/Kamon#704]
### Expected behavior

The Play application server should start normally with an alternative config file

```
[info] Running the application with Aspectj Weaver
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)
```

### Actual behavior 
However, with an alternate configuration file the following issue is seen:
```
[info] Running the application with Aspectj Weaver
--- (Running the application, auto-reloading is enabled) ---

[error] Caused by: java.io.IOException: resource not found on classpath: test.conf
[error] 	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
[error] 	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
[error] 	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
[error] 	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error] 	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
[error] 	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:957)
[error] 	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:885)
[error] 	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
[error] 	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
[error] 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:259)
[error] 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:256)
[error] 	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
[error] 	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
[error] 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:256)
[error] 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:232)
[error] 	at kamon.Kamon$.<init>(Kamon.scala:35)
[error] 	at kamon.Kamon$.<clinit>(Kamon.scala)
[error] 	at kamon.context.HasContext$.fromCurrentContext(Mixin.scala:44)
[error] 	at kamon.scala.instrumentation.FutureInstrumentation.mixinTraceContextAwareToFutureRelatedRunnable(FutureInstrumentation.scala:29)
...
[error] (Compile / run) java.lang.reflect.InvocationTargetException
[error] Total time: 4 s, completed 4 Apr, 2018 12:31:06 PM
[INFO] [04/04/2018 12:31:06.464] [Thread-2] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

### Steps to reproduce the behavior
```
➜ sbt "run -Dconfig.resource=test.conf"
```

### Dependency versions
```
Play version: 2.6.11
kamon-play-2.6: 1.0.1
sbt-aspectj-runner-play-2.6: 1.1.0

```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
