### ISSUE TITLE
Status page embedded server error when restarting play app in dev mode

### ISSUE THREAD

**Issue by alvaroc1** [kamon-io/Kamon#710]
Kamon 2.0. I don't think it's causing any issues, just the error displayed in the console. The kamon status page still renders fine. But probably worth either adding a shutdown hook to the module so the status page embedded server turns off when the app is off... or handle it more gracefully if we don't want to restart the embedded server on play restart.

```
[info] k.i.p.GuiceModule$KamonLoader - Reconfiguring Kamon with Play's Config
[error] kamon.status.page.StatusPage - Failed to start the status page embedded server
java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.bind(ServerSocket.java:329)
        at kamon.lib.fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1761)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
