### ISSUE TITLE
kamon-influxdb can't be initialized when using `kamon.reporters` in application.conf since 1.0.2

### ISSUE THREAD

**Issue by danbim** [kamon-io/Kamon#737]
Since I switched to `kamon-influxdb` in version `1.0.2` in order to use basic authentication with InfluxDB the plugin stopped working when using `kamon.reporters = ["kamon.influxdb.InfluxDBReporter"]` in `application.conf`.

It fails with the following stack trace:
```
2019-02-18 13:27:44,020 [ERROR] kamon.ReporterRegistry [main] - Failed to load configured reporter [kamon.influxdb.InfluxDBReporter]
java.lang.NoSuchMethodException: kamon.influxdb.InfluxDBReporter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at kamon.util.DynamicAccess.$anonfun$createInstanceFor$1(DynamicAccess.scala:44)
	at scala.util.Try$.apply(Try.scala:209)
	at kamon.util.DynamicAccess.createInstanceFor(DynamicAccess.scala:41)
	at kamon.util.DynamicAccess.$anonfun$createInstanceFor$4(DynamicAccess.scala:52)
	at scala.util.Success.flatMap(Try.scala:247)
	at kamon.util.DynamicAccess.createInstanceFor(DynamicAccess.scala:52)
	at kamon.ReporterRegistry$Default.$anonfun$loadReportersFromConfig$1(ReporterRegistry.scala:88)
	at kamon.ReporterRegistry$Default.$anonfun$loadReportersFromConfig$1$adapted(ReporterRegistry.scala:86)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kamon.ReporterRegistry$Default.loadReportersFromConfig(ReporterRegistry.scala:86)
	at kamon.Kamon$.loadReportersFromConfig(Kamon.scala:147)
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
