### ISSUE TITLE
JVM crashes 

### ISSUE THREAD

**Issue by MChouaiar** [kamon-io/Kamon#757]
Hello,
We are experiencing some shutdowns of our JVM with this error message :

2020-03-05 12:50:05,418 [prometheus] ERROR kamon.module.ModuleRegistry Reporter [prometheus] failed to process a metrics tick.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.reflect.ManifestFactory$ByteManifest.newArray(Manifest.scala:173)
	at scala.reflect.ManifestFactory$ByteManifest.newArray(Manifest.scala:171)
	at scala.Array$.ofDim(Array.scala:316)
	at kamon.metric.Histogram$DistributionSnapshotBuilder.snapshot(Histogram.scala:149)
	at kamon.metric.Histogram$DistributionSnapshotBuilder.snapshot$(Histogram.scala:110)
	at kamon.metric.Distribution$LocalHistogram.snapshot(Distribution.scala:343)
	at kamon.metric.Distribution$.merge(Distribution.scala:154)
	at kamon.metric.Distribution$.merge(Distribution.scala:143)
	at kamon.metric.PeriodSnapshot$Accumulator.$anonfun$accumulateDistribution$1(PeriodSnapshot.scala:198)
	at kamon.metric.PeriodSnapshot$Accumulator$$Lambda$1846/889244581.apply(Unknown Source)
	at kamon.metric.PeriodSnapshot$Accumulator.$anonfun$accumulate$2(PeriodSnapshot.scala:220)
	at kamon.metric.PeriodSnapshot$Accumulator$$Lambda$1872/1130432567.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:312)
	at kamon.metric.PeriodSnapshot$Accumulator.accumulate(PeriodSnapshot.scala:216)
	at kamon.metric.PeriodSnapshot$Accumulator.accumulateDistribution(PeriodSnapshot.scala:198)
	at kamon.metric.PeriodSnapshot$Accumulator.$anonfun$add$4(PeriodSnapshot.scala:114)
	at kamon.metric.PeriodSnapshot$Accumulator.$anonfun$add$4$adapted(PeriodSnapshot.scala:114)
	at kamon.metric.PeriodSnapshot$Accumulator$$Lambda$1847/802395528.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:312)
	at kamon.metric.PeriodSnapshot$Accumulator.add(PeriodSnapshot.scala:114)
	at kamon.prometheus.PrometheusReporter.reportPeriodSnapshot(PrometheusReporter.scala:63)
	at kamon.module.ModuleRegistry$$anon$1.$anonfun$run$2(ModuleRegistry.scala:176)
	at kamon.module.ModuleRegistry$$anon$1$$Lambda$1839/1106213742.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:660)
	at scala.concurrent.Future$$$Lambda$607/215734628.apply(Unknown Source)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Does anyone have any idea about the possible root cause of it ?

Thanks in advance.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
