### ISSUE TITLE
Kamon breaks "affinity-pool-executor"

### ISSUE THREAD

**Issue by eugenemiretsky** [kamon-io/Kamon#776]
Kamon seems to break (bring app down), when using  affinity-pool-executor

`
20:29:03
at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)

20:29:03
at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)

20:29:03
at akka.dispatch.Mailbox.run(Mailbox.scala:228)

20:29:03
at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedThreadPool$TimingRunnable.run(ExecutorInstrumentation.scala:437)

20:29:03
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

20:29:03
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

20:29:03
at java.lang.Thread.run(Thread.java:748)

20:29:03
Caused by: java.lang.NullPointerException: null
Caused by: java.lang.NullPointerException: null

20:29:03
at kamon.instrumentation.akka.instrumentations.akka_25.InstrumentNewExecutorServiceOnAkka25$.around(DispatcherInstrumentation.scala:143)
	at kamon.instrumentation.akka.instrumentations.akka_25.InstrumentNewExecutorServiceOnAkka25$.around(DispatcherInstrumentation.scala:143)

20:29:03
at akka.dispatch.affinity.AffinityPoolConfigurator$$anon$1.createExecutorService(AffinityPool.scala)
	at akka.dispatch.affinity.AffinityPoolConfigurator$$anon$1.createExecutorService(AffinityPool.scala)

20:29:03
at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor$lzycompute(Dispatcher.scala:43)

20:29:03
at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor(Dispatcher.scala:43)`

**Comment by dlmutart** [comment]
I'm also seeing a NPE with Kamon as soon as I add an affinity-pool-executor to my configuration. 

[ERROR] [07/13/2020 11:54:09.375] [ClusterSystem-akka.actor.default-dispatcher-2] [akka://ClusterSystem/user] null
java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at kamon.util.Filter$Glob.accept(Filter.scala:197)
        at kamon.util.Filter$IncludeExclude.$anonfun$includes$1(Filter.scala:140)
        at kamon.util.Filter$IncludeExclude.$anonfun$includes$1$adapted(Filter.scala:140)
        at scala.collection.LinearSeqOptimized.exists(LinearSeqOptimized.scala:95)
        at scala.collection.LinearSeqOptimized.exists$(LinearSeqOptimized.scala:92)
        at scala.collection.immutable.List.exists(List.scala:89)
        at kamon.util.Filter$IncludeExclude.includes(Filter.scala:140)
        at kamon.util.Filter$IncludeExclude.accept(Filter.scala:137)
        at kamon.instrumentation.akka.instrumentations.InstrumentNewExecutorServiceOnAkka25$.around(DispatcherInstrumentation.scala:155)
        at akka.dispatch.affinity.AffinityPoolConfigurator$$anon$1.createExecutorService(AffinityPool.scala)
        at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor$lzycompute(Dispatcher.scala:43)
        at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor(Dispatcher.scala:43)
        at akka.dispatch.ExecutorServiceDelegate.execute(ThreadPoolBuilder.scala:217)
        at akka.dispatch.ExecutorServiceDelegate.execute$(ThreadPoolBuilder.scala:217)
        at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:42)
        at akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:126)
        at akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:140)
        at akka.actor.dungeon.Dispatch.start(Dispatch.scala:116)
        at akka.actor.dungeon.Dispatch.start$(Dispatch.scala:114)
        at akka.actor.ActorCell.start(ActorCell.scala:447)
        at akka.actor.ActorCell.start(ActorCell.scala:447)
        at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:111)
        at akka.actor.ActorCell.handleSupervise(ActorCell.scala:720)
        at akka.actor.ActorCell.supervise(ActorCell.scala:706)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:554)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
        at akka.dispatch.Mailbox.run(Mailbox.scala:228)
        at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:653)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by wfudeacon97** [comment]
We've hit a similar issue.  We were not hitting this issue when running on OpenJdk 8, but we did hit this issue with OpenJdk11.  On OpenJdk 11, the issue presents with both Kanela-agent 1.0.0 and 1.0.6.  The issue goes away when I change my executor away from an affinity-pool.

We are working with kamon-bundle_2.13: 2.1.4 and akka 2.13 (multiple libraries) version: 2.5.24.

Has anyone found a solution to this problem?

**Comment by dlmutart** [comment]
> I'm also seeing a NPE with Kamon as soon as I add an affinity-pool-executor to my configuration.
> 
> [ERROR] [07/13/2020 11:54:09.375] [ClusterSystem-akka.actor.default-dispatcher-2] [akka://ClusterSystem/user] null
> java.lang.NullPointerException
> at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
> at java.util.regex.Matcher.reset(Matcher.java:309)
> at java.util.regex.Matcher.(Matcher.java:229)
> at java.util.regex.Pattern.matcher(Pattern.java:1093)
> at kamon.util.Filter$Glob.accept(Filter.scala:197)
> at kamon.util.Filter$IncludeExclude.$anonfun$includes$1(Filter.scala:140)
> at kamon.util.Filter$IncludeExclude.$anonfun$includes$1$adapted(Filter.scala:140)
> at scala.collection.LinearSeqOptimized.exists(LinearSeqOptimized.scala:95)
> at scala.collection.LinearSeqOptimized.exists$(LinearSeqOptimized.scala:92)
> at scala.collection.immutable.List.exists(List.scala:89)
> at kamon.util.Filter$IncludeExclude.includes(Filter.scala:140)
> at kamon.util.Filter$IncludeExclude.accept(Filter.scala:137)
> at kamon.instrumentation.akka.instrumentations.InstrumentNewExecutorServiceOnAkka25$.around(DispatcherInstrumentation.scala:155)
> at akka.dispatch.affinity.AffinityPoolConfigurator$$anon$1.createExecutorService(AffinityPool.scala)
> at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor$lzycompute(Dispatcher.scala:43)
> at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor(Dispatcher.scala:43)
> at akka.dispatch.ExecutorServiceDelegate.execute(ThreadPoolBuilder.scala:217)
> at akka.dispatch.ExecutorServiceDelegate.execute$(ThreadPoolBuilder.scala:217)
> at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:42)
> at akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:126)
> at akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:140)
> at akka.actor.dungeon.Dispatch.start(Dispatch.scala:116)
> at akka.actor.dungeon.Dispatch.start$(Dispatch.scala:114)
> at akka.actor.ActorCell.start(ActorCell.scala:447)
> at akka.actor.ActorCell.start(ActorCell.scala:447)
> at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:111)
> at akka.actor.ActorCell.handleSupervise(ActorCell.scala:720)
> at akka.actor.ActorCell.supervise(ActorCell.scala:706)
> at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:554)
> at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
> at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
> at akka.dispatch.Mailbox.run(Mailbox.scala:228)
> at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:653)
> at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
> at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

We are seeing it on Java HotSpot(TM) 64-Bit Server VM (build 25.261-b25, mixed mode)
