### ISSUE TITLE
[spans-ingestion] request declined, unknown error

### ISSUE THREAD

**Issue by AlexITC** [kamon-io/Kamon#783]
I'm trying Kamon and suddenly my server started reporting this warning, any reason for this and what should I do?

```
[spans-ingestion] request declined, unknown error
    at kamon.apm.KamonApmApiClient.postWithRetry(KamonApmApiClient.scala:94)
    at kamon.apm.KamonApmApiClient.postSpans(KamonApmApiClient.scala:32)
    at kamon.apm.KamonApm.$anonfun$reportSpans$2(KamonApm.scala:82)
    at kamon.apm.KamonApm.$anonfun$reportSpans$2$adapted(KamonApm.scala:82)
    at scala.Option.foreach(Option.scala:407)
    at kamon.apm.KamonApm.reportSpans(KamonApm.scala:82)
    at kamon.module.ModuleRegistry$$anon$2.$anonfun$run$4(ModuleRegistry.scala:214)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```

Thanks.

**Comment by t-bast** [comment]
I'm seeing the same thing regularly.
I'm wondering where we can get more information to troubleshoot this.
It's likely rate-limiting coming from Kamon's servers?

**Comment by AlexITC** [comment]
This is another one similar I see frequently:
```
[metrics-ingestion] request declined, unknown error
    at kamon.apm.KamonApmApiClient.postWithRetry(KamonApmApiClient.scala:94)
    at kamon.apm.KamonApmApiClient.postIngestion(KamonApmApiClient.scala:23)
    at kamon.apm.KamonApm.$anonfun$reportIngestion$7(KamonApm.scala:113)
    at kamon.apm.KamonApm.$anonfun$reportIngestion$7$adapted(KamonApm.scala:113)
    at scala.Option.foreach(Option.scala:407)
    at kamon.apm.KamonApm.$anonfun$reportIngestion$1(KamonApm.scala:113)
    at kamon.apm.KamonApm.$anonfun$reportIngestion$1$adapted(KamonApm.scala:89)
    at scala.Option.foreach(Option.scala:407)
```

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
