### ISSUE TITLE
[kamon-akka-http] Instrumentation  crashes on akka-http 10.2.0

### ISSUE THREAD

**Issue by lvitaly** [kamon-io/Kamon#835]
kanela-agent 1.0.6
kamon 2.1.4
akka 2.6.8
akka-http 10.2.0
```
ERROR: Error => akka.http.scaladsl.server.directives.RouteDirectives with message None of [public static akka.http.scaladsl.server.directives.CompleteOrRecoverWithMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.marshalling.Marshaller), public static akka.http.scaladsl.server.directives.OnSuccessMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.server.util.Tupler), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.redirect(akka.http.scaladsl.model.Uri,akka.http.scaladsl.model.StatusCodes$Redirection), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.complete(scala.Function0), public static akka.http.scaladsl.server.Directive kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.onComplete(scala.Function0), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.failWith(java.lang.Throwable)] allows for delegation from public akka.http.scaladsl.server.StandardRoute akka.http.scaladsl.server.directives.RouteDirectives.complete(akka.http.scaladsl.model.StatusCode,scala.Function0,akka.http.scaladsl.marshalling.Marshaller). Class loader: jdk.internal.loader.ClassLoaders$AppClassLoader@42a57993: java.lang.IllegalArgumentException: None of [public static akka.http.scaladsl.server.directives.CompleteOrRecoverWithMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.marshalling.Marshaller), public static akka.http.scaladsl.server.directives.OnSuccessMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.server.util.Tupler), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.redirect(akka.http.scaladsl.model.Uri,akka.http.scaladsl.model.StatusCodes$Redirection), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.complete(scala.Function0), public static akka.http.scaladsl.server.Directive kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.onComplete(scala.Function0), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.failWith(java.lang.Throwable)] allows for delegation from public akka.http.scaladsl.server.StandardRoute akka.http.scaladsl.server.directives.RouteDirectives.complete(akka.http.scaladsl.model.StatusCode,scala.Function0,akka.http.scaladsl.marshalling.Marshaller)
	at kanela.agent.libs.net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1096)
	at kanela.agent.libs.net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1346)
	at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
	at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
	at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:5228)
	at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1487)
	at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:718)
	at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:401)
	at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3827)
	at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
	at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:252)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10327)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10029)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10722)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10660)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10219)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	...
	at microservice.Main$.<clinit>(Main.scala:14)
	at microservice.Main.main(Main.scala)
```

**Comment by ivantopo** [comment]
Just got this PR running to fix this issue: https://github.com/kamon-io/Kamon/pull/838
