### ISSUE TITLE
NoSuchMethorError when upgrading to Kamon 2.1.5

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#844]
From [Gitter](https://gitter.im/kamon-io/Kamon?at=5f493efd765d633c54bbe426): 

Hello. After updating to the latest kamon 2.1.5 I observed that a simple sbt test that has been running smoothly with kamon 2.14 is now broken and this is the error:

```
java.lang.NoSuchMethodError: 'akka.actor.ActorRef akka.actor.ActorRefProvider.ignoreRef()' at 
akka.actor.typed.internal.adapter.ActorSystemAdapter.<init>(ActorSystemAdapter.scala:82) at 
akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension.<init>(ActorSystemAdapter.scala:135) at 
akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension$.createExtension(ActorSystemAdapter.scala:142) at 
akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension$.createExtension(ActorSystemAdapter.scala:138) at 
akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1009) at akka.actor.ExtensionId.apply(Extension.scala:80) at 
akka.actor.ExtensionId.apply$(Extension.scala:79) at 
akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension$.apply(ActorSystemAdapter.scala:138) at 
akka.actor.typed.internal.adapter.ActorSystemAdapter$.apply(ActorSystemAdapter.scala:131) at 
akka.actor.typed.internal.adapter.ActorContextAdapter.<init>(ActorContextAdapter.scala:59) at 
akka.actor.typed.internal.adapter.ActorAdapter.ctx(ActorAdapter.scala:65) at 
akka.actor.typed.internal.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:255) at 
akka.actor.ActorCell.create(ActorCell.scala:678) at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:549) at 
akka.actor.ActorCell.systemInvoke(ActorCell.scala:571) at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293) 
at akka.dispatch.Mailbox.run(Mailbox.scala:228) at akka.dispatch.Mailbox.exec(Mailbox.scala:241) at 
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) at 
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) at 
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) at 
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ivantopo** [comment]
The issue here is that I left some dependencies unattended on the Play gRPC tests and that caused an entire Akka version to be shaded in the kamon-bundle. Fix coming in a minute.
