### ISSUE TITLE
kamon-play-example

### ISSUE THREAD

**Issue by justjoheinz** [kamon-io/Kamon#94]
In my attempt to get kamon running I started to use the kamon-play-example project.

I plain sbt run compiles everything, but of course I will not see any datapoints due to lack of aspectj instrumentation.

Starting the application with 
```
SBT_OPTS="-javaagent:aspectjweaver-1.8.1.jar" sbt run
```
results in the following error message:
```
objc[40627]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[info] Loading global plugins from /Users/markusklink/.sbt/0.13/plugins
[info] Loading project definition from /Users/markusklink/Documents/inoio/Kamon/kamon-examples/kamon-play-example/project
[info] Set current project to Kamon-Play-Example (in build file:/Users/markusklink/Documents/inoio/Kamon/kamon-examples/kamon-play-example/)
[info] Updating {file:/Users/markusklink/Documents/inoio/Kamon/kamon-examples/kamon-play-example/}Kamon-Play-Example...
[info] Resolving jline#jline;2.11 ...
[info] downloading http://snapshots.kamon.io/io/kamon/kamon-core_2.11/0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9/kamon-core_2.11-0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9.jar ...
[info] 	[SUCCESSFUL ] io.kamon#kamon-core_2.11;0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9!kamon-core_2.11.jar (1955ms)
[info] downloading http://snapshots.kamon.io/io/kamon/kamon-play_2.11/0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9/kamon-play_2.11-0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9.jar ...
[info] 	[SUCCESSFUL ] io.kamon#kamon-play_2.11;0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9!kamon-play_2.11.jar (790ms)
[info] downloading http://snapshots.kamon.io/io/kamon/kamon-statsd_2.11/0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9/kamon-statsd_2.11-0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9.jar ...
[info] 	[SUCCESSFUL ] io.kamon#kamon-statsd_2.11;0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9!kamon-statsd_2.11.jar (788ms)
[info] downloading http://snapshots.kamon.io/io/kamon/kamon-log-reporter_2.11/0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9/kamon-log-reporter_2.11-0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9.jar ...
[info] 	[SUCCESSFUL ] io.kamon#kamon-log-reporter_2.11;0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9!kamon-log-reporter_2.11.jar (774ms)
[info] downloading http://snapshots.kamon.io/io/kamon/kamon-system-metrics_2.11/0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9/kamon-system-metrics_2.11-0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9.jar ...
[info] 	[SUCCESSFUL ] io.kamon#kamon-system-metrics_2.11;0.3.4-05453bdeb54f4db8f643185c28fec34a77ef5ca9!kamon-system-metrics_2.11.jar (4727ms)
[info] Done updating.

[URLClassLoader@7ae079f5] error Cannot instantiate message handler kamon.weaver.logging.KamonWeaverMessageHandler -- (ConfigException$Missing) No configuration setting found for key 'kamon'
No configuration setting found for key 'kamon'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'kamon'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:147)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:218)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:224)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:33)
	at kamon.weaver.logging.KamonWeaverMessageHandler.<init>(KamonWeaverMessageHandler.scala:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

this is also the error message, I usually see when I try kamon on my own projects, and which has been reported infrequently on mailinglists, etc.

If I do ```sbt stage``` and then from the ```target/universal/stage``` directory a ```java -cp ".:lib/*" -javaagent:lib/org.aspectj.aspectjweaver-1.8.1.jar play.core.server.NettyServer``` as described in the play controller, I get the following exception:
```
Play server process ID is 40753
[INFO] [10/17/2014 09:39:21.079] [main] [StatsDExtension(akka://application)] Starting the Kamon(StatsD) extension
[INFO] [10/17/2014 09:39:21.156] [main] [SystemMetricsExtension(akka://application)] Starting the Kamon(SystemMetrics) extension
[INFO] [10/17/2014 09:39:21.263] [main] [LogReporterExtension(akka://application)] Starting the Kamon(LogReporter) extension
[info] play - Starting application default Akka system.
[INFO] [10/17/2014 09:39:21.310] [main] [PlayExtension(akka://application)] Starting the Kamon(Play) extension
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[ERROR] [10/17/2014 09:39:22.219] [application-akka.actor.default-dispatcher-7] [akka://application/user/kamon-log-reporter] / by zero
java.lang.ArithmeticException: / by zero
	at kamon.logreporter.LogReporterSubscriber$RichHistogramSnapshot.average(LogReporter.scala:309)
	at kamon.logreporter.LogReporterSubscriber.logCpuMetrics(LogReporter.scala:147)
	at kamon.logreporter.LogReporterSubscriber$$anonfun$printMetricSnapshot$1.apply(LogReporter.scala:91)
	at kamon.logreporter.LogReporterSubscriber$$anonfun$printMetricSnapshot$1.apply(LogReporter.scala:84)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at kamon.logreporter.LogReporterSubscriber.printMetricSnapshot(LogReporter.scala:84)
	at kamon.logreporter.LogReporterSubscriber$$anonfun$receive$1.applyOrElse(LogReporter.scala:74)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at kamon.logreporter.LogReporterSubscriber.aroundReceive(LogReporter.scala:70)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487)
	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at akka.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:56)
	at akka.actor.ActorCell.invoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [10/17/2014 09:39:23.132] [application-akka.actor.default-dispatcher-9] [akka://application/user/kamon-log-reporter] 
+--------------------------------------------------------------------------------------------------+
|                                                                                                  |
|    CPU (ALL)                                                                                     |
|                                                                                                  |
|    User (percentage)       System (percentage)    Wait (percentage)   Idle (percentage)          |
|       Min: 41                    Min: 3                 Min: 0             Min: 56               |
```

and still do not see datapoints (which might be my problem). Before I continue to investigate, I would like to know whether these are known problems, or if I am doing something fundamentally wrong.

I am on Mac OS X 10.9.5 and java 1.8.0_11. Thanks.

**Comment by dpsoft** [comment]
Play have some limitations when trying to set a java agent in Play dev mode (ie, play run) -> https://github.com/playframework/playframework/issues/1372

**Comment by dpsoft** [comment]
@magro @justjoheinz,  Guys we have been worked in a sbt plugin that allow perform LTW in sbt and we will be able to do run in development mode in play seamlessly. sbt-aspectj-runner. Enjoy!!!!!

**Comment by magro** [comment]
Great, thanks!
