### ISSUE TITLE
still scala.util.Success cannot be cast to kamon.instrumentation.context.HasContext with kamon 2.1.12

### ISSUE THREAD

**Issue by mrt181** [kamon-io/Kamon#957]
Happens for me too:

jdk: adopt-openjdk-11.0.10
scala: 2.13.5
sbt: 1.4.7
akka: 2.6.13
kamon: 2.1.12

starting only with `-javaagent:kanela-agent.jar`, no sbt-kanela-runner, no sbt-javaagent

and this Main
```scala
object Main extends App {
  Kamon.init()
  println(Banner.text)
  val userSystem: ActorSystem[Protocol] =
    ActorSystem[Protocol](Protocol(), "mySystem")
}
```
The moment I initialize the userSystem I get these errors.
```
 _  __                _        ______
| |/ /               | |       \ \ \ \
| ' / __ _ _ __   ___| | __ _   \ \ \ \
|  < / _` | '_ \ / _ \ |/ _` |   ) ) ) )
| . \ (_| | | | |  __/ | (_| |  / / / /
|_|\_\__,_|_| |_|\___|_|\__,_| /_/_/_/
                              
==============================
Running with Kanela, the Kamon Instrumentation Agent :: (v1.0.8)

2021-03-10T15:49:12.596Z INFO  [              main]         kamon.status.page.StatusPage  - Status page started on http://0.0.0.0:5266/
2021-03-10T15:49:12.897Z DEBUG [              main] re.os.windows.WindowsOperatingSystem  - Debug privileges not enabled.
2021-03-10T15:49:13.002Z INFO  [              main]  kamon.prometheus.PrometheusReporter  - Started the embedded HTTP server on http://0.0.0.0:9095/metrics
java.lang.ClassCastException: class scala.util.Success cannot be cast to class kamon.instrumentation.context.HasContext (scala.util.Success and kamon.instrumentation.context.HasContext are in unnamed module of loader 'app')
```

Adding a `Thread.sleep(20000)` before starting the userSystem fixes the error messages. waiting 10 sec is not enough

_Originally posted by @mrt181 in https://github.com/kamon-io/Kamon/issues/601#issuecomment-795650096_

**Comment by mrt181** [comment]
@dpsoft removing `Kamon.init()` does not stop the errors from popping up. But It does stop the status page and the metric enpoint for prometheus from starting.

```
 _  __                _        ______
| |/ /               | |       \ \ \ \
| ' / __ _ _ __   ___| | __ _   \ \ \ \
|  < / _` | '_ \ / _ \ |/ _` |   ) ) ) )
| . \ (_| | | | |  __/ | (_| |  / / / /
|_|\_\__,_|_| |_|\___|_|\__,_| /_/_/_/
                              
==============================
Running with Kanela, the Kamon Instrumentation Agent :: (v1.0.8)

2021-03-10T20:55:49.021Z INFO  [fault-dispatcher-3]         akka.event.slf4j.Slf4jLogger  - Slf4jLogger started
[order-book-store-akka.actor.default-dispatcher-3] ERROR 2021-03-10 21:55:49  Logger : An error occurred while trying to apply an advisor: java.lang.ClassCastException: class scala.util.Success cannot be cast to class kamon.instrumentation.context.HasContext (scala.util.Success and kamon.instrumentation.context.HasContext are in unnamed module of loader 'app')
	at kamon.instrumentation.futures.scala.CallbackRunnableRunInstrumentation$.enter(FutureChainingInstrumentation.scala:76)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:419)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:299)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
	at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:620)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:106)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:56)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) 
[order-book-store-akka.actor.default-dispatcher-3] ERROR 2021-03-10 21:55:49  Logger : An error occurred while trying to apply an advisor: java.lang.NullPointerException
	at kamon.instrumentation.futures.scala.CallbackRunnableRunInstrumentation$.exit(FutureChainingInstrumentation.scala:86)```

**Comment by mrt181** [comment]
Tried again with `kamon-bundle`. Could start my app three times in a row without errors, then on the next start it threw errors again and kept throwing them on subsequent starts (with `Kamon.init()`)

Removing `kamon-bundle` and setting my dependencies like this works:
```sbt
    libraryDependencies ++= Seq(
      library.kamonCore,
      library.kamonStatusPage    % Runtime,
      library.kamonPrometheus    % Runtime,
      library.kamonSystemMetrics % Runtime,
      library.kamonExecutors     % Runtime,
      library.kamonAkka          % Runtime,
      library.kamonAkkaHttp      % Runtime,
    )
```

no more errors at all. Can it be cause by the bundle and the instrumentation?

**Comment by dpsoft** [comment]
@mrt181 thanks for sharing! Running with `java -javaagent:kanela-agent.jar my-assembly.jar` you still experimenting errors? in that case, which errors?

**Comment by mrt181** [comment]
The `java -javaagent:kanela-agent.jar my-assembly.jar` approach work app. 4 of 5 times without errors.
In the error case I get this initially, it does not show up later when I keep my app running.

```logback
[my-project-akka.actor.default-dispatcher-3] ERROR 2021-03-12 10:33:02  Logger : An error occurred while trying to apply an advisor: java.lang.ClassCastException: class scala.util.Success cannot be cast to class kamon.instrumentation.context.HasContext (scala.util.Success and kamon.instrumentation.context.HasContext are in unnamed module of loader 'app')
        at kamon.instrumentation.futures.scala.CallbackRunnableRunInstrumentation$.enter(FutureChainingInstrumentation.scala:76)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:419)
        at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
        at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
        at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:299)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
        at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:620)
        at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:106)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:56)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[my-project-akka.actor.default-dispatcher-3] ERROR 2021-03-12 10:33:02  Logger : An error occurred while trying to apply an advisor: java.lang.NullPointerException
        at kamon.instrumentation.futures.scala.CallbackRunnableRunInstrumentation$.exit(FutureChainingInstrumentation.scala:86)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
        at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
        at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:299)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
        at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:620)
        at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:106)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:56)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by SimunKaracic** [comment]
Can You try again with Kamon 2.1.14? If the error persists, please add the following settings, and show us the output (from start of app, untill the first error):
kanela {
  debug-mode = true
  log-level = "DEBUG"
}

**Comment by odd** [comment]
I got it to work by adding a monitoring trait (see below) and extending that in my main class/object (it has to be to the left of any other super traits/classes which might utilize futures or any other class which is instrumented by Kamon).
```scala
trait Monitoring {
  Kamon.init()
}
object Main extends Monitoring with ....
```

**Comment by alejandrod-f** [comment]
Similar problem here:
`java.lang.ClassCastException: akka.dispatch.Envelope cannot be cast to kamon.instrumentation.context.HasContext`

Looks like timing in the initialization. Hard to say

Most of the times fails. But, sometimes is ok. 
sbt 1.5.3
scala 2.13.6
kamon 2.2.1
Play 2.8.8

**Comment by ivantopo** [comment]
I'm not sure if it is related, but I know we have an issue with the sbt-kanela-runner-play when running on development mode. Is that your case @alejandrod-f? If it is, try using Play 2.8.7 until we figure out how to publish a new version of the plugin. Otherwise, share here and we'll figure it out!

**Comment by alejandrod-f** [comment]
Well, the only thing that made this error to go away was to downgrade Kamon to 2.1.3 (from 2.2.1)
Now I get a single error log. Which looks ok compared with hundreds of error logs. 

Is hard to provide an example that will reproduce the issue. 

`[main] ERROR 2021-07-02 12:52:31  Logger : Error => akka.http.scaladsl.server.directives.RouteDirectives with message None of [public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.complete(scala.Function0), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.redirect(akka.http.scaladsl.model.Uri,akka.http.scaladsl.model.StatusCodes$Redirection), public static akka.http.scaladsl.server.Directive kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.onComplete(scala.Function0), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.failWith(java.lang.Throwable), public static akka.http.scaladsl.server.directives.OnSuccessMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.server.util.Tupler), public static akka.http.scaladsl.server.directives.CompleteOrRecoverWithMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.marshalling.Marshaller)] allows for delegation from public akka.http.scaladsl.server.StandardRoute akka.http.scaladsl.server.directives.RouteDirectives.complete(akka.http.scaladsl.model.StatusCode,scala.Function0,akka.http.scaladsl.marshalling.Marshaller). Class loader: sun.misc.Launcher$AppClassLoader@18b4aac2: java.lang.IllegalArgumentException: None of [public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.complete(scala.Function0), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.redirect(akka.http.scaladsl.model.Uri,akka.http.scaladsl.model.StatusCodes$Redirection), public static akka.http.scaladsl.server.Directive kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.onComplete(scala.Function0), public static akka.http.scaladsl.server.StandardRoute kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.failWith(java.lang.Throwable), public static akka.http.scaladsl.server.directives.OnSuccessMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.server.util.Tupler), public static akka.http.scaladsl.server.directives.CompleteOrRecoverWithMagnet kamon.instrumentation.akka.http.ResolveOperationNameOnRouteInterceptor.apply(scala.Function0,akka.http.scaladsl.marshalling.Marshaller)] allows for delegation from public akka.http.scaladsl.server.StandardRoute akka.http.scaladsl.server.directives.RouteDirectives.complete(akka.http.scaladsl.model.StatusCode,scala.Function0,akka.http.scaladsl.marshalling.Marshaller)`
