### ISSUE TITLE
Updating play 2.8 version breaks tests

### ISSUE THREAD

**Issue by SimunKaracic** [kamon-io/Kamon#967]
Running `+test` causes the following error on play 2.8.3 or higher:
```
[info] WSInstrumentationSpec:
[info] kamon.instrumentation.play.WSInstrumentationSpec *** ABORTED ***
[info]   com.google.inject.CreationException: Unable to create injector, see the following errors:
[info] 
[info] 1) A binding to akka.actor.ClassicActorSystemProvider was already configured at play.grpc.ClassicActorsystemProviderModule.<init>(ClassicActorsystemProviderModule.scala:13):
[info] Binding(interface akka.actor.ClassicActorSystemProvider to ProviderConstructionTarget(class play.api.libs.concurrent.ActorSystemProvider)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4).
[info]   at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.apply(BuiltinModule.scala:80):
[info] Binding(interface akka.actor.ClassicActorSystemProvider to ProviderConstructionTarget(class play.api.libs.concurrent.ClassicActorSystemProviderProvider)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
[info] 
[info] 1 error
[info]   at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
[info]   at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
[info]   at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
[info]   at com.google.inject.Guice.createInjector(Guice.java:87)
[info]   at com.google.inject.Guice.createInjector(Guice.java:78)
[info]   at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
[info]   at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
[info]   at kamon.instrumentation.play.WSInstrumentationSpec.fakeApplication(WSInstrumentationSpec.scala:51)
[info]   at org.scalatestplus.play.BaseOneServerPerSuite.app(BaseOneServerPerSuite.scala:142)
[info]   at org.scalatestplus.play.BaseOneServerPerSuite.app$(BaseOneServerPerSuite.scala:142)
[info]   ...
```

**Comment by LinnielDW** [comment]
Facing the same issue. @SimunKaracic did you ever find a solution?
